apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    {{- include "common.labels.componentSelectorLabels" (list "server" .) | nindent 4 }}
  ports:
    - name: demo-issuer-ws-http
      port: 3007
      targetPort: wallet-port
      protocol: TCP
