{{ $name := include "common.names.fullname" . }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name }}-migrations
  labels:
    app.kubernetes.io/name: {{ $name }}-migrations
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      {{- with .Values.migration.labels }}
      labels:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.nameOverride | default .Chart.Name }}-migrations
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.imageMigrations.repository }}:{{ .Values.image.tag }}"
          args: ["fresh"]
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-cluster-demo-issuer-app
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-cluster-demo-issuer-app
                  key: password
            - name: DATABASE_URL
              value: "postgres://$(DB_USERNAME):$(DB_PASSWORD)@db-cluster-demo-issuer-rw:5432/issuance_server"
      restartPolicy: Never
