apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    service: demo-issuer-issuance-server
spec:
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
    {{- if .Values.extraPodlabels }}
    {{ toYaml .Values.extraPodlabels | nindent 4 }}
    {{- end }}
  ports:
    - name: demo-issuer-ws-http
      port: 3007
      targetPort: wallet-port
      protocol: TCP
