# This component library YAML file is included
# by the public and private OpenAP documents.
components:
  schemas:
    session_request:
      description: A session request post body
      type: object
      properties:
        usecase:
          type: string
        items_requests:
          type: array
          items:
            $ref: '#/components/schemas/item_requests'
        return_url_template:
          type: string
          format: uri
      required:
        - usecase
        - items_requests
        - return_url_template

    item_requests:
      type: object
      properties:
        docType:
          $ref: '#/components/schemas/doc_type'
        nameSpaces:
          $ref: '#/components/schemas/namespaces'

    doc_type:
      type: string
      enum:
        - com.example.pid
        - com.example.address

    namespaces:
      type: object
      properties:
        com.example.pid:
          type: object
          properties:
            given_name: boolean
            family_name: boolean
            given_name_birth: boolean
            family_name_birth: boolean
            gender: boolean
            birth_date: boolean
            age_over_18: boolean
            birth_place: boolean
            birth_city: boolean
            birth_state: boolean
            birth_country: boolean
            bsn: boolean
          additionalProperties: false
        com.example.address:
          type: object
          properties:
            resident_address: boolean
            resident_street: boolean
            resident_house_number: boolean
            resident_postal_code: boolean
            resident_city: boolean
            resident_state: boolean
            resident_country: boolean
          additionalProperties: false
      additionalProperties: false

    session_token:
      description: The unique identifier of a session
      type: string
      minLength: 32
      maxLength: 32
      pattern: '^[a-zA-Z0-9]{32}$'

    session_type:
      description: The type of the session
      type: string
      enum:
        - cross_device
        - same_device

    session_status:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
          - CREATED
          - WAITING_FOR_RESPONSE
          - DONE
          - FAILED
          - CANCELLED
          - EXPIRED
        ul:
          type: string
          format: uri

    token_response:
      description: An object containing a session token
      type: object
      required:
        - session_token
      properties:
        session_token:
          $ref: '#/components/schemas/session_token'

    disclosed_attributes:
      description: An object with the resultant disclosed attributes
      type: object
      properties:
        com.example.pid:
          type: object
          properties:
            attributes:
              $ref: '#/components/schemas/attributes'
            issuer:
              type: string
            ca:
              type: string
            validityInfo:
              $ref: '#/components/schemas/validity_info'
          required:
            - attributes
            - issuer
            - validityInfo
        com.example.address:
          type: object
          properties:
            attributes:
              $ref: '#/components/schemas/attributes'
            issuer:
              type: string
            ca:
              type: string
            validityInfo:
              $ref: '#/components/schemas/validity_info'
          required:
            - attributes
            - issuer
            - validityInfo
        additionalProperties: false

    attributes:
      type: object
      additionalProperties: true
      example:
        attributeName: attributeValue

    validity_info:
      type: object
      properties:
        signed:
          type: string
          format: date-time
        validFrom:
          type: string
          format: date-time
        validUntil:
          type: string
          format: date-time
      required:
        - signed
        - validFrom
        - validUntil

    error_message:
      type: object
      required:
        - type
        - title
        - status
        - detail
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: int
        detail:
          type string

    ephemeral_id:
      description: An ephemeral id
      type: string

    time:
      description: Time in RFC 3339 format
      type: string
      format: date-time

    wallet_nonce:
      description: A cryptographic nonce
      type: object
      required:
        - wallet_nonce
      properties:
        wallet_nonce: string

    vp_token:
      description: A verifiable presentation token
      type: object
      required:
        - vp_token
      properties:
        vp_token: string

    redirect_object:
      description: A redirect object
      type: object
      required:
        - redirect_uri
      properties:
        redirect_uri:
          type: string
          format: uri

    oauth_authz_data:
      description: Oauth authz data
      type: string
