include: ./../../analysis_options.yaml

linter:
  rules:
    prefer_const_constructors: true

analyzer:
  exclude:
    # exclude all generated source code
    - "lib/src/api/**"
    - "lib/src/models/**"
    - "lib/src/frb_generated*"
