include: ./../../analysis_options.yaml

linter:
  rules:
  # Optionally add or exclude extra rules

analyzer:
  exclude:
    # exclude all generated source code
    - "lib/src/api/**"
    - "lib/src/models/**"
    - "lib/src/frb_generated*"
