## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
## @section Global parameters
## @param global.imageRegistry Global Docker image registry
##
global:
  imageRegistry: ""

## @section Common parameters
## Number of replicas
## @param replicaCount Number of replicas
##
replicaCount: 1

## @section Image parameters
## @param image.repository Repository for the container image
## @param image.pullPolicy Image pull policy
## @param image.tag Image tag
##
image:
  repository: ghcr-io-proxy/brp-api/haal-centraal-brp-bevragen-gba-mock
  pullPolicy: IfNotPresent
  tag: "latest"

## @section Image pull secrets
## Secrets for pulling images from private registries
## @param imagePullSecrets Array of secret names for private registries
##
imagePullSecrets: []

## @section Common parameters
## String to partially override the chart's fullname template
## @param nameOverride String to partially override chart's fullname
##
nameOverride: ""

## @section Pod labels
## Additional labels for the pods
## @param extraPodlabels Additional labels for the pods
##
extraPodlabels: {}

## @section Resource requests and limits
## @param resources.limits.memory Memory limit
## @param resources.limits.cpu CPU limit
## @param resources.requests.memory Memory request
## @param resources.requests.cpu CPU request
##
resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi

## @section GbaMock parameters
## Parameters for the GbaMock configuration
## @param gbaMock.enabled Enable or disable the GbaMock deployment
##
gbaMock:
  enabled: true
