include:
  - "deploy/gitlab/**.yml"

default:
  image: "${HARBOR_REGISTRY}/${HARBOR_PROJECT}/nl-wallet-app-builder-ci-base:${BUILD_TAG}"

variables:
  CACHE_COMPRESSION_LEVEL: "fastest"
  FF_USE_FASTZIP: "true"
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: "line-tables-only"
  APP_BUILD_OFFSET: 861
  BUILD_TAG: 250715-08bed29b
  HSM_CLIENT_TAG: "61581018"
  BUNDLE_DEPLOYMENT: "true"
  BUNDLE_RETRY: 10

# Kubernetes is used to deploy, but also to access our secrets for various services.
# By default it uses the GitLab CI variables, but can be overridden using the variables repo.
# Note this dual uses requires the secrets to live in the k8s environment that is also used for CI testing.
.env-k8s:
  environment:
    name: ${K8S_CLUSTER}
    action: access
    kubernetes:
      namespace: ${K8S_NAMESPACE}

.env-macos-runner:
  tags:
    - macos
  image: sonoma-wallet:0.1.12

.default-branch:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "parent_pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        CACHE_POLICY: pull-push

.release-tag:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
      when: never
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
      variables:
        CACHE_POLICY: pull

.merge-request:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      interruptible: true
      variables:
        CACHE_POLICY: pull

.merge-request-manual:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      interruptible: true
      variables:
        CACHE_POLICY: pull
      when: manual
      # jobs that have "when: manual" in rules are non optional in Gitlab CI/CD
      allow_failure: true

.default-or-release:
  rules:
    - !reference [.default-branch, rules]
    - !reference [.release-tag, rules]

.default-or-merge-request:
  rules:
    - !reference [.default-branch, rules]
    - !reference [.merge-request, rules]

.default-or-release-or-merge-request:
  rules:
    - !reference [.default-or-release, rules]
    - !reference [.merge-request, rules]

.default-or-release-or-merge-request-manual:
  rules:
    - !reference [.default-or-release, rules]
    - !reference [.merge-request-manual, rules]

.on-schedule:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline" && $SCHEDULED == "true"

.on-mock-build:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline" && $BUILD == "mock"

.on-demo-build:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline" && $BUILD == "demo"

.ruby-cache:
  cache:
    key: ruby-${CI_COMMIT_REF_SLUG}
    paths:
      - "vendor/bundle"

.ruby-cache-macos:
  extends: .ruby-cache
  cache:
    key: ruby-macos-${CI_COMMIT_REF_SLUG}
