name: nl_wallet_workspace

environment:
  sdk: ^3.12.2
  flutter: ^3.44.0

publish_to: none

workspace:
  - wallet_app
  - wallet_app/plugins/bluetooth
  - wallet_app/packages/wallet_core
  - wallet_app/packages/wallet_mock
