// ignore_for_file: constant_identifier_names
/// Flutter icons WalletIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WalletIcons
///      fonts:
///       - asset: fonts/WalletIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class WalletIcons {
  WalletIcons._();

  static const _kFontFam = 'WalletIcons';
  static const String? _kFontPkg = null;

  static const IconData icon_face_id = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
