[test-groups]
gba-pid = { max-threads = 2 }
db-hsm = { max-threads = 1 }
mock-oidc = { max-threads = 1 }
mock-mdoc-disclosure-session = { max-threads = 1 }
mock-digid-session = { max-threads = 1 }
mock-issuance-session = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'package(/^tests_integration/) & (kind(test) & binary(gba_pid_test))'
test-group = 'gba-pid'

[[profile.default.overrides]]
filter = 'package(/^tests_integration/) | (kind(test) & (package(wallet_provider*) | package(pid_issuer) | package(verification_server) | package(hsm)))'
test-group = 'db-hsm'

[[profile.default.overrides]]
filter = 'package(wallet) & test(/^issuance::app2app/)'
test-group = 'mock-oidc'

[[profile.default.overrides]]
filter = 'package(wallet) & test(/wallet::disclosure::tests::.+disclosure/)'
test-group = 'mock-mdoc-disclosure-session'

[[profile.default.overrides]]
filter = 'package(wallet) & test(/test_create_pid_issuance_auth_url(|_error_digid_session_start)$/)'
test-group = 'mock-digid-session'

[[profile.default.overrides]]
filter = 'package(wallet) & test(/test_continue_pid_issuance(|_error_(pid_issuer|document))$/)'
test-group = 'mock-issuance-session'

[profile.ci]
fail-fast = false

[profile.ci.junit]
path = "junit.xml"
