[test-groups]
# Not needed for `hsm`
MockPkcePair = { max-threads = 1 }
MetricsRecorder = { max-threads = 1 }
# Not needed for `MockCloseProximityDisclosureClient`

[[profile.default.overrides]]
filter = 'package(=openid4vc) & test(/::test_auth_url::/)'
test-group = 'MockPkcePair'

[[profile.default.overrides]]
filter = 'package(=measure) & binary(=measure_tests)'
test-group = 'MetricsRecorder'

[profile.ci]
fail-fast = false

[profile.ci.junit]
path = "junit.xml"
