[test-groups]
hsm = { max-threads = 1 }
mock-pkce = { max-threads = 1 }
metrics-recorder = { max-threads = 1 }
# Not needed for `MockCloseProximityDisclosureClient`

[[profile.default.overrides]]
# Include all tests_integration because not all of the tests can run independently inbetween binaries
filter = 'package(tests_integration) | (package(wallet_provider) & binary(hsm)) | (package(hsm) & binary(hsm))'
test-group = 'hsm'

[[profile.default.overrides]]
filter = 'package(openid4vc) & test(/(test_start_and_into_token_request|test_user_cancels)$/)'
test-group = 'mock-pkce'

[[profile.default.overrides]]
filter = 'package(measure) & binary(measure_tests)'
test-group = 'metrics-recorder'

[profile.ci]
fail-fast = false

[profile.ci.junit]
path = "junit.xml"
