[test-groups]
# Not needed for `hsm`
mock-pkce = { max-threads = 1 }
metrics-recorder = { max-threads = 1 }
# Not needed for `MockCloseProximityDisclosureClient`

[[profile.default.overrides]]
filter = 'package(openid4vc) & test(/(test_start_and_into_token_request|test_user_cancels)$/)'
test-group = 'mock-pkce'

[[profile.default.overrides]]
filter = 'package(measure) & binary(measure_tests)'
test-group = 'metrics-recorder'

[profile.ci]
fail-fast = false

[profile.ci.junit]
path = "junit.xml"
