[package]
name = "issuer_settings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
chrono.workspace = true
derive_more = { workspace = true, features = ["as_ref", "from"] }
futures = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
rustls-pki-types.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

crypto.path = "../../lib/crypto"
hsm = { path = "../../lib/hsm", features = ["settings"] }
mdoc.path = "../../lib/mdoc"
openid4vc.path = "../../lib/openid4vc"
sd_jwt_vc_metadata.path = "../../lib/sd_jwt_vc_metadata"
wallet_common.path = "../../lib/wallet_common"
server_utils.path = "../server_utils"

[dev-dependencies]
assert_matches.workspace = true

crypto = { path = "../../lib/crypto", features = ["generate", "mock"] }
mdoc = { path = "../../lib/mdoc", features = ["generate", "mock"] }
openid4vc = { path = "../../lib/openid4vc", features = ["mock"] }
sd_jwt_vc_metadata = { path = "../../lib/sd_jwt_vc_metadata", features = ["example_constructors"] }
server_utils = { path = "../server_utils", features = ["integration_test"] }
