[package]
name = "issuer_settings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
chrono.workspace = true
derive_more = { workspace = true, features = ["as_ref", "from"] }
futures = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
rustls-pki-types.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

crypto.path = "../../crypto"
hsm = { path = "../../hsm", features = ["settings"] }
mdoc.path = "../../mdoc"
openid4vc.path = "../../openid4vc"
sd_jwt_vc_metadata.path = "../../sd_jwt_vc_metadata"
wallet_common.path = "../../wallet_common"
server_utils.path = "../server_utils"
