apiVersion: v2
name: database-cnpg
description: A Helm chart for CloudNative-PG database clusters

type: application

version: 2.6.0

appVersion: "16.7-bookworm"

dependencies:
  - name: sp-common
    repository: "file://../sp-common"
    version: 1.x.x
