apiVersion: v1
kind: Service
metadata:
  name: brpproxy
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.extraPodLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
