// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'frb_generated.dart';

enum FlutterApiErrorType {
  /// This version of the app is blocked.
  VersionBlocked,

  /// A network connection has timed-out, was unable to connect or something else went wrong during the request.
  Networking,

  /// The request failed, but the server did send a response.
  Server,

  /// Something went wrong during issuance that's caused by the issuer.
  Issuer,

  /// Something went wrong during disclosure that's caused by the verifier.
  Verifier,

  /// The wallet is in an unexpected state.
  WalletState,

  /// Failed to finish the DigiD session and get an authorization code.
  RedirectUri,

  /// Device does not support hardware backed keys.
  HardwareKeyUnsupported,

  /// The disclosure URI source (universal link or QR code) does not match the received session type.
  DisclosureSourceMismatch,

  /// A remote session is expired, the user may or may not be able to retry the operation.
  ExpiredSession,

  /// A remote session is cancelled.
  CancelledSession,

  /// The wrong DigiD was used for PID renewal or PIN recovery.
  WrongDigid,

  /// DigiD authentication was cancelled.
  DeniedDigid,

  /// Wallet has been revoked.
  Revoked,

  /// Indicating something unexpected went wrong.
  Generic,
}
