//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "attestation_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i16,
    #[sea_orm(unique)]
    pub name: String,
    pub next_sequence_no: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::status_list::Entity")]
    StatusList,
}

impl Related<super::status_list::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StatusList.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
