//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "attestation_batch_list_indices")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub attestation_batch_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub status_list_id: i64,
    pub indices: Vec<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::attestation_batch::Entity",
        from = "Column::AttestationBatchId",
        to = "super::attestation_batch::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AttestationBatch,
    #[sea_orm(
        belongs_to = "super::status_list::Entity",
        from = "Column::StatusListId",
        to = "super::status_list::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    StatusList,
}

impl Related<super::attestation_batch::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AttestationBatch.def()
    }
}

impl Related<super::status_list::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StatusList.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
