apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.extraPodlabels }}
          {{ toYaml .Values.extraPodlabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml . | nindent 10 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ include "common.names.fullname" . }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- with .Values.resources }}
          resources:
          {{ toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.nameOverride | default .Chart.Name }}-port
              containerPort: 3007
          volumeMounts:
            - name: pid-issuer-private-keys
              mountPath: /pid_issuer.toml
              subPath: pid_issuer.toml
            - name: pid-issuer-metadata
              mountPath: /eudi:pid:1.json
              subPath: eudi:pid:1.json
            - name: pid-issuer-metadata
              mountPath: /eudi:pid:nl:1.json
              subPath: eudi:pid:nl:1.json
            - name: pid-issuer-metadata
              mountPath: /eudi:pid-address:1.json
              subPath: eudi:pid-address:1.json
            - name: pid-issuer-metadata
              mountPath: /eudi:pid-address:nl:1.json
              subPath: eudi:pid-address:nl:1.json
          env:
            - name: PID_ISSUER__WALLET_SERVER__PORT
              value: "3007"
            - name: PID_ISSUER__PUBLIC_URL
              value: {{ include "common.urls.combineDomainAndContext" (list .Values.ingress.hostname .Values.ingress.contextPath) }}
            - name: PID_ISSUER__STRUCTURED_LOGGING
              value: "true"
            - name: PID_ISSUER__ISSUER_TRUST_ANCHORS
              valueFrom:
                configMapKeyRef:
                  name: nl-wallet-server-trust-anchors
                  key: issuer_trust_anchors
            - name: PID_ISSUER__DIGID__BSN_PRIVKEY
              valueFrom:
                secretKeyRef:
                  name: nl-pid-issuer-digid-bsn-privkey
                  key: bsn_privkey
            - name: PID_ISSUER__DIGID__HTTP_CONFIG__BASE_URL
              value: {{ include "common.urls.combineDomainAndContext" (list .Values.digid.hostname .Values.digid.contextPath) }}
            - name: PID_ISSUER__DIGID__HTTP_CONFIG__TRUST_ANCHORS
              valueFrom:
                configMapKeyRef:
                  name: nl-pid-issuer-digid-http-trust-anchors
                  key: trust_anchors
            - name: PID_ISSUER__BRP_SERVER
              value: "http://brpproxy:5001/"
            - name: PID_ISSUER__WTE_ISSUER_PUBKEY
              valueFrom:
                configMapKeyRef:
                  name: nl-pid-issuer-wte-issuer-pubkey
                  key: wte_issuer_pubkey
            - name: PID_ISSUER__METADATA
              value: "eudi:pid:1.json,eudi:pid:nl:1.json,eudi:pid-address:1.json,eudi:pid-address:nl:1.json"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-cluster-pi-app
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-cluster-pi-app
                  key: password
            - name: PID_ISSUER__STORAGE__URL
              value: "postgres://$(DB_USERNAME):$(DB_PASSWORD)@db-cluster-pi-rw:5432/pid_issuer"
            - name: RUST_LOG
              value: "debug,hyper=warn"
      volumes:
        - name: pid-issuer-private-keys
          secret:
            secretName: nl-pid-issuer-private-keys
        - name: pid-issuer-metadata
          configMap:
            name: nl-wallet-pid-issuer-metadata
