apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
    {{- if .Values.extraPodlabels }}
    {{ toYaml .Values.extraPodlabels | nindent 4 }}
    {{- end }}
  ports:
    - name: pid-issuer-http
      port: 3007
      targetPort: pid-issuer-port
      protocol: TCP
