//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "status_list_item")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub attestation_type_id: i16,
    #[sea_orm(primary_key, auto_increment = false)]
    pub sequence_no: i64,
    pub status_list_id: i64,
    pub index: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
