//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wallet_user_apple_attestation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub assertion_counter: i64,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub attestation_data: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::wallet_user::Entity")]
    WalletUser,
}

impl Related<super::wallet_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalletUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
