//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wallet_user_apple_attestation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub wallet_user_id: Uuid,
    pub assertion_counter: i64,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))")]
    pub attestation_data: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wallet_user::Entity",
        from = "Column::WalletUserId",
        to = "super::wallet_user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WalletUser,
}

impl Related<super::wallet_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WalletUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
