[package]
name = "update_policy_model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
indexmap = { workspace = true, features = ["serde"] }
semver = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true, features = ["base64"] }
strum = { workspace = true, features = ["derive"] }
thiserror.workspace = true

[dev-dependencies]
rstest.workspace = true
serde_json = { workspace = true, features = ["std"] }
