apiVersion: v2
type: application
name: admin-portal
version: 0.1.0
appVersion: ""
description: A Helm chart for the Wallet Admin Portal

dependencies:
  - name: sp-common
    repository: "file://../sp-common"
    version: 1.x.x
