apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.componentSelectorLabels" (list "server" .) | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        {{- include "common.labels.componentSelectorLabels" (list "server" .) | nindent 8 }}
        {{- if .Values.extraPodLabels }}
        {{- toYaml .Values.extraPodLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "common.names.fullname" . }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8001
            - name: http-internal
              containerPort: 8002
          volumeMounts:
            - name: config-volume
              mountPath: /verification_server.toml
              subPath: config.toml
          env:
            - name: VERIFICATION_SERVER__REQUESTER_SERVER__IP
              value: "0.0.0.0"
            - name: VERIFICATION_SERVER__PUBLIC_URL
              value: {{ include "common.urls.combineDomainAndContext" (list .Values.ingress.hostname .Values.ingress.contextPath) }}
            - name: VERIFICATION_SERVER__UNIVERSAL_LINK_BASE_URL
              value: {{ .Values.universalLinkBaseUrl }}
            - name: VERIFICATION_SERVER__STRUCTURED_LOGGING
              value: "true"
            - name: VERIFICATION_SERVER__STORAGE__URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: url
            - name: VERIFICATION_SERVER__ISSUER_TRUST_ANCHORS
              valueFrom:
                configMapKeyRef:
                  name: nl-wallet-server-trust-anchors
                  key: issuer_trust_anchors
            - name: VERIFICATION_SERVER__READER_TRUST_ANCHORS
              valueFrom:
                configMapKeyRef:
                  name: nl-wallet-server-trust-anchors
                  key: reader_trust_anchors
            - name: VERIFICATION_SERVER__EPHEMERAL_ID_SECRET
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-demo-rp-verification-server-verifier-ephemeral-id-secret
                  key: verifier_ephemeral_id_secret
            - name: VERIFICATION_SERVER__USECASES__mijn_amsterdam__CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-demo-rp-verification-server-verifier-usecases-mijn-amsterdam
                  key: certificate
            - name: VERIFICATION_SERVER__USECASES__mijn_amsterdam__PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-demo-rp-verification-server-verifier-usecases-mijn-amsterdam
                  key: private_key
            - name: VERIFICATION_SERVER__USECASES__mijn_amsterdam__PRIVATE_KEY_TYPE
              value: "software"
            - name: VERIFICATION_SERVER__USECASES__monkey_bike__CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-demo-rp-verification-server-verifier-usecases-monkey-bike
                  key: certificate
            - name: VERIFICATION_SERVER__USECASES__monkey_bike__PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-demo-rp-verification-server-verifier-usecases-monkey-bike
                  key: private_key
            - name: VERIFICATION_SERVER__USECASES__monkey_bike__PRIVATE_KEY_TYPE
              value: "software"
            - name: VERIFICATION_SERVER__USECASES__online_marketplace__CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-demo-rp-verification-server-verifier-usecases-online-marketplace
                  key: certificate
            - name: VERIFICATION_SERVER__USECASES__online_marketplace__PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-demo-rp-verification-server-verifier-usecases-online-marketplace
                  key: private_key
            - name: VERIFICATION_SERVER__USECASES__online_marketplace__PRIVATE_KEY_TYPE
              value: "software"
            - name: VERIFICATION_SERVER__USECASES__xyz_bank__CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-demo-rp-verification-server-verifier-usecases-xyz-bank
                  key: certificate
            - name: VERIFICATION_SERVER__USECASES__xyz_bank__PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-demo-rp-verification-server-verifier-usecases-xyz-bank
                  key: private_key
            - name: VERIFICATION_SERVER__USECASES__xyz_bank__PRIVATE_KEY_TYPE
              value: "software"
            - name: VERIFICATION_SERVER__USECASES__job_finder__CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-demo-rp-verification-server-verifier-usecases-job-finder
                  key: certificate
            - name: VERIFICATION_SERVER__USECASES__job_finder__PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-demo-rp-verification-server-verifier-usecases-job-finder
                  key: private_key
            - name: VERIFICATION_SERVER__USECASES__job_finder__PRIVATE_KEY_TYPE
              value: "software"
            - name: RUST_LOG
              value: "debug,hyper=warn"
      volumes:
        - name: config-volume
          configMap:
            name: nl-wallet-demo-rp-verification-server-data
