{{ if .Values.migration.reset }}
{{ $name := include "common.names.fullname" . }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $name }}-reset
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  schedule: "0 0 * * *"
  suspend: true
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      backoffLimit: 1
      template:
        metadata:
          labels:
            {{- include "common.labels.component" (list "reset" .) | nindent 12 }}
            {{- with .Values.migration.labels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Values.nameOverride | default .Chart.Name }}-migrations
              image: "{{ .Values.global.imageRegistry }}/{{ .Values.imageMigrations.repository }}:{{ .Values.image.tag }}"
              args: ["fresh"]
              {{- with .Values.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.database.secretName }}
                      key: url
          restartPolicy: Never
{{- end }}
