#include "PlatformSupport-Bridging-Header.h"
#include "attested_key_integration_tests.h"
#include "hw_keystore_integration_tests.h"
#include "close_proximity_disclosure_integration_tests.h"
#include "utils_integration_tests.h"
