## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
## @section Global parameters
## @param global.imageRegistry Global Docker image registry
##
global:
  imageRegistry: ""

## @section Common parameters
## Number of replicas
## @param replicaCount Number of replicas
##
replicaCount: 1

## @section Image parameters
## @param image.repository Repository for the container image
## @param image.pullPolicy Image pull policy
## @param image.tag Image tag
##
image:
  repository: ghcr-io-proxy/brp-api/haal-centraal-brp-bevragen-proxy
  pullPolicy: IfNotPresent
  tag: "2.1.2"

## @section Image pull secrets
## Secrets for pulling images from private registries
## @param imagePullSecrets Array of secret names for private registries
##
imagePullSecrets: []

## @section Common parameters
## String to partially override the chart's fullname template
## @param nameOverride String to partially override chart's fullname
##
nameOverride: ""

## @section Pod labels
## Additional labels for the pods
## @param extraPodlabels Additional labels for the pods
##
extraPodlabels: {}

## @section Resource requests and limits
## @param resources.limits.memory Memory limit
## @param resources.limits.cpu CPU limit
## @param resources.requests.memory Memory request
## @param resources.requests.cpu CPU request
##
resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi

## @section Environment variables
## Environment variables for the container
## @param env[0].name Name of Routes__0__DownstreamScheme environment variable
## @param env[0].value Value of Routes__0__DownstreamScheme environment variable
## @param env[1].name Name of Routes__0__DownstreamHostAndPorts__0__Host environment variable
## @param env[1].value Value of Routes__0__DownstreamHostAndPorts__0__Host environment variable
## @param env[2].name Name of Routes__0__DownstreamHostAndPorts__0__Port environment variable
## @param env[2].value Value of Routes__0__DownstreamHostAndPorts__0__Port environment variable
##
env:
  - name: Routes__0__DownstreamScheme
    value: "http"
  - name: Routes__0__DownstreamHostAndPorts__0__Host
    value: "gba-hc-converter"
  - name: Routes__0__DownstreamHostAndPorts__0__Port
    value: "3006"
