apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
  ports:
    - name: demo-relying-party-http
      port: 3004
      targetPort: demo-rp-port
      protocol: TCP
