{{ if .Values.gbaEncryptTestData.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-xml-files
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{ with .Values.xmlFiles }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
