apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-zoek-xml
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{ with .Values.zoekXmlFiles }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
