apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    {{- include "common.labels.component" (list .Values.frontend.name .) | nindent 4 }}
spec:
  selector:
    {{- include "common.labels.componentSelectorLabels" (list .Values.frontend.name .) | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
