{{ $configMapFile := (print $.Template.BasePath "/cm-gba-hc-converter-zoek-xml.yaml") }}
{{ $configMapChecksum := sha256sum (tpl (print $configMapFile) .) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.component" (list .Chart.Name .) | nindent 4 }}
spec:
  replicas: {{ .Values.gbaHcConverter.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.componentSelectorLabels" (list .Chart.Name .) | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 300
  template:
    metadata:
      annotations:
        checksum/config: "{{ $configMapChecksum }}"
      labels:
        {{- include "common.labels.componentSelectorLabels" (list .Chart.Name .) | nindent 8 }}
        {{ with .Values.gbaHcConverter.extraPodlabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "common.names.fullname" . }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ with .Values.gbaHcConverter.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: preloaded-gba-v-data-volume
              mountPath: /resources/encrypted-gba-v-responses
              readOnly: true
            - mountPath: /resources/remote/bsn_zoeken_template.xml
              name: zoek-xml-volume
              subPath: bsn_zoeken_template.xml
          ports:
            - name: http
              containerPort: 8001
          env:
            - name: RUST_BACKTRACE
              value: "1"
            - name: RUST_LOG
              value: "debug,hyper=warn"
            - name: GBA_HC_CONVERTER__STRUCTURED_LOGGING
              value: "true"
            {{ if or (eq .Values.gbaHcConverter.runMode "PRELOADED") (eq .Values.gbaHcConverter.runMode "ALL") }}
            - name: GBA_HC_CONVERTER__RUN_MODE__{{ .Values.gbaHcConverter.envVarNamePreloaded }}__XML_PATH
              value: {{ .Values.gbaHcConverter.preloadedXmlPath }}
            - name: GBA_HC_CONVERTER__RUN_MODE__{{ .Values.gbaHcConverter.envVarNamePreloaded }}__ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: encryption_key
            - name: GBA_HC_CONVERTER__RUN_MODE__{{ .Values.gbaHcConverter.envVarNamePreloaded }}__HMAC_KEY
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: hmac_key
            {{ end }}

            {{ if or (eq .Values.gbaHcConverter.runMode "GBAV") (eq .Values.gbaHcConverter.runMode "ALL") }}
            - name: GBA_HC_CONVERTER__RUN_MODE__{{ .Values.gbaHcConverter.envVarNameGbav }}__ADHOC_URL
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: adhoc_url
            - name: GBA_HC_CONVERTER__RUN_MODE__{{ .Values.gbaHcConverter.envVarNameGbav }}__USERNAME
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: username
            - name: GBA_HC_CONVERTER__RUN_MODE__{{ .Values.gbaHcConverter.envVarNameGbav }}__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: password
            - name: GBA_HC_CONVERTER__RUN_MODE__{{ .Values.gbaHcConverter.envVarNameGbav }}__CLIENT_CERTIFICATE_AND_KEY__CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: client_cert
            - name: GBA_HC_CONVERTER__RUN_MODE__{{ .Values.gbaHcConverter.envVarNameGbav }}__CLIENT_CERTIFICATE_AND_KEY__KEY
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: client_cert_key
            - name: GBA_HC_CONVERTER__RUN_MODE__{{ .Values.gbaHcConverter.envVarNameGbav }}__TRUST_ANCHOR
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: trust_anchor
            {{ end }}

      volumes:
        - name: preloaded-gba-v-data-volume
          persistentVolumeClaim:
            claimName: preloaded-gba-v-data-pvc
            readOnly: true
        - name: zoek-xml-volume
          configMap:
            name: {{ include "common.names.fullname" . }}-zoek-xml

      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
