apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.preloadGba.volumeClaimName }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: nfs
