apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.extraPodlabels }}
        {{- toYaml .Values.extraPodlabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "common.names.fullname" . }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8001
          volumeMounts:
            - name: config-volume
              mountPath: /demo_relying_party.toml
              subPath: config.toml
          env:
            - name: DEMO_RELYING_PARTY__PUBLIC_WALLET_SERVER_URL
              value: {{ .Values.verificationServerBaseUrl }}
            - name: DEMO_RELYING_PARTY__INTERNAL_WALLET_SERVER_URL
              value: "http://demo-rp-verification-server:8080/"
            - name: DEMO_RELYING_PARTY__PUBLIC_URL
              value: {{ include "common.urls.combineDomainAndContext" (list .Values.ingress.hostname .Values.ingress.contextPath) }}
            - name: DEMO_RELYING_PARTY__HELP_BASE_URL
              value: {{ .Values.helpBaseUrl }}
            - name: DEMO_RELYING_PARTY__DEMO_INDEX_URL
              value: {{ .Values.demoIndexUrl }}
            - name: DEMO_RELYING_PARTY__STRUCTURED_LOGGING
              value: "true"
            - name: DEMO_RELYING_PARTY__LOG_REQUESTS
              value: {{ .Values.logRequests | quote }}
            - name: RUST_LOG
              value: "debug,hyper=warn"
      volumes:
        - name: config-volume
          configMap:
            name: nl-wallet-demo-relying-party-data
