[package]
name = "entity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
chrono.workspace = true
derive_more = { workspace = true, features = ["constructor"] }
sea-orm = { workspace = true, features = ["macros", "with-json", "with-uuid", "with-chrono"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
uuid.workspace = true

attestation_data.path = "../../lib/attestation_data"
sd_jwt_vc_metadata.path = "../../lib/sd_jwt_vc_metadata"
