apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  wallet_provider.toml: |
    [recovery_code_paths]
    {{ .Values.recoveryCodePaths | toToml }}
