{{ $name := include "common.names.fullname" . }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name }}-migrations
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "common.labels.component" (list "migration" .) | nindent 8 }}
        {{- with .Values.migration.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $name }}-migrations
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.imageMigrations.repository }}:{{ .Values.image.tag }}"
          args: ["up"]
          env:
            - name: WALLET_PROVIDER__DATABASE__HOST
              value: db-cluster-rw
            - name: WALLET_PROVIDER__DATABASE__NAME
              valueFrom:
                secretKeyRef:
                  name: db-cluster-app
                  key: dbname
            - name: WALLET_PROVIDER__DATABASE__USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-cluster-app
                  key: username
            - name: WALLET_PROVIDER__DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-cluster-app
                  key: password
      restartPolicy: Never
