{{ $fullName := include "common.names.fullname" . }}
{{ $host := print .Release.Name "-pooler-rw" }}
{{ if not .Values.pooling.enabled }}
  {{ $host = print .Release.Name "-rw" }}
{{ end }}
{{ $port := "5432" }}
---
{{ $argsMigrator := dict "release" .Release "name" .Values.users.migrator.nameSecret }}
{{ $secretMigrator := include "common.secrets.getSecretByName" $argsMigrator | trim }}
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ .Values.users.migrator.nameSecret | quote }}
data:
  dbname: {{ .Values.database.name | b64enc | quote }}
  jdbc-uri: {{ print "jdbc:postgresql://" $host "." .Release.Namespace ".svc:" $port "/" .Values.database.name "?user=" .Values.users.migrator.name "&password=" $secretMigrator| b64enc | quote }}
  uri: {{ print "postgresql://" $host "." .Release.Namespace ".svc:" $port "/" .Values.database.name "?user=" .Values.users.migrator.name "&password=" $secretMigrator| b64enc | quote }}
  host: {{ $host | b64enc | quote }}
  port: {{ $port | b64enc | quote }}
  user: {{ .Values.users.migrator.name | b64enc | quote }}
  username: {{ .Values.users.migrator.name | b64enc | quote }}
  password: {{ $secretMigrator | b64enc | quote }}
  pgpass: {{ print $host ":" $port ":" .Values.database.name ":" .Values.users.migrator.name ":" $secretMigrator | b64enc | quote }}
