## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
## @section Global parameters
## @param global.imageRegistry Global Docker image registry
##
global:
  imageRegistry: ""

## @section Common parameters
## String to partially override the chart's fullname template
## @param nameOverride String to partially override chart's fullname
##
nameOverride: ""

## @section Common parameters
## Number of replicas
## @param replicaCount Number of replicas
##
replicaCount: 2

## @section Image parameters
## @param image.repository Repository for the container image
## @param image.pullPolicy Image pull policy
## @param image.tag Image tag
##
image:
  repository: null
  pullPolicy: IfNotPresent
  tag: null

## @section Image migration parameters
## @param imageMigrations.repository Repository for the migration container image
## @param imageMigrations.pullPolicy Image pull policy for the migration container
##
imageMigrations:
  repository: null
  pullPolicy: IfNotPresent

## @section Pod labels
## Additional labels for the pods
## @param extraPodlabels Additional labels for the pods
##
extraPodlabels: {}

## @section Image pull secrets
## Secrets for pulling images from private registries
## @param imagePullSecrets Array of secret names for private registries
##
imagePullSecrets: []

## @section Ingress VPN parameters
## Parameters for the VPN ingress
## @param ingressVpn.hostname Hostname for the VPN ingress
##
ingressVpn:
  hostname: null

## @section Ingress parameters
## Parameters for the ingress configuration
## @param ingress.enabled Enable or disable the ingress
## @param ingress.className Ingress class name
## @param ingress.tlsSecretName Name of the TLS secret for the ingress
## @param ingress.labels Additional labels for the ingress
##
ingress:
  enabled: true
  className: "nginx"
  tlsSecretName: null
  labels: {}

## @section Resource requests and limits
## @param resources.requests.cpu CPU request
## @param resources.requests.memory Memory request
## @param resources.limits.cpu CPU limit
## @param resources.limits.memory Memory limit
##
resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

## @section Verification Server parameters
## Parameters for the verification server configuration
## @param verificationServer.hostname Hostname for the verification server
## @param verificationServer.contextPath Context path for the verification server
##
verificationServer:
  hostname: null
  contextPath: null

## @param universalLinkBaseUrl Base URL for universal links
universalLinkBaseUrl: null

## @section Migration parameters
## Parameters for the migration configuration
## @param migration.labels Additional labels for the migration job
## @param migration.reset Enable reset cron job
##
migration:
  labels: {}
  reset: true
