[webserver]
ip = '127.0.0.1'
port = 3011

[[usecases.university.9999999999]]
attestation_type = "com.example.degree"

[usecases.university.9999999999.attributes]
university = "University Holland"
education = "MSc Economics"
graduation_date = "1970-01-01"
grade = 7
cum_laude = false

[[usecases.insurance.9999999999]]
attestation_type = "com.example.insurance"

[usecases.insurance.9999999999.attributes]
product = "Health Insurance"
coverage = "Basic"
start_date = "2025-01-01"
duration = 365
customer_number = "283728"
