apiVersion: apps/v1
kind: Deployment
metadata:
  name: gba-fetch-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gba-fetch-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: gba-fetch-frontend
        tier: vertrouwd
        ingress-controller-frontoffice-policy: allow
        egress-frontoffice-policy: allow
    spec:
      imagePullSecrets:
        - name: harbor-puller
      serviceAccountName: sp-nonroot
      securityContext:
        runAsUser: 65532
      containers:
        - name: gba-fetch-frontend
          image: $GBA_FETCH_FRONTEND_IMAGE
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "50m"
          volumeMounts:
            - name: preloaded-gba-v-data-volume
              mountPath: /data
            - mountPath: /resources/remote/bsn_zoeken_template.xml
              name: zoek-xml-volume
              subPath: bsn_zoeken_template.xml
          env:
            - name: RUST_BACKTRACE
              value: "1"
            - name: RUST_LOG
              value: "debug,hyper=warn"
            - name: GBA_HC_CONVERTER__STRUCTURED_LOGGING
              value: "true"
            - name: GBA_HC_CONVERTER__PORT
              value: "3000"
            - name: GBA_HC_CONVERTER__RUN_MODE__ALL__PRELOADED__XML_PATH
              value: "/data"
            - name: GBA_HC_CONVERTER__RUN_MODE__ALL__PRELOADED__ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: encryption_key
            - name: GBA_HC_CONVERTER__RUN_MODE__ALL__PRELOADED__HMAC_KEY
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: hmac_key
            - name: GBA_HC_CONVERTER__RUN_MODE__ALL__GBAV__ADHOC_URL
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: adhoc_url
            - name: GBA_HC_CONVERTER__RUN_MODE__ALL__GBAV__USERNAME
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: username
            - name: GBA_HC_CONVERTER__RUN_MODE__ALL__GBAV__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: password
            - name: GBA_HC_CONVERTER__RUN_MODE__ALL__GBAV__CLIENT_CERT
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: client_cert
            - name: GBA_HC_CONVERTER__RUN_MODE__ALL__GBAV__CLIENT_CERT_KEY
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: client_cert_key
            - name: GBA_HC_CONVERTER__RUN_MODE__ALL__GBAV__TRUST_ANCHOR
              valueFrom:
                secretKeyRef:
                  name: nl-wallet-gba-hc-converter-secrets
                  key: trust_anchor
      volumes:
        - name: preloaded-gba-v-data-volume
          persistentVolumeClaim:
            claimName: preloaded-gba-v-data-pvc
        - name: zoek-xml-volume
          configMap:
            name: nl-wallet-gba-hc-converter-zoek-xml
      hostAliases:
        - ip: 147.181.7.110
          hostnames:
            - lap.gbav.idm.diginetwerk.net
