apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-zoek-xml
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
{{- range $path, $bytes := .Files.Glob (printf "files/*") }}
{{ base $path | indent 2 }}: |
{{ tpl ($.Files.Get $path) $ | indent 4 }}
{{- end }}
