apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
  ports:
    - name: gba-hc-http
      port: 3006
      targetPort: 3006
