apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gba-in-zeer-vertrouwd
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              gba-in-zeer-vertrouwd: allow
  podSelector:
    matchLabels:
      {{- include "common.labels.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
