apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    service: mrp-verification-server
spec:
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
    {{- if .Values.extraPodlabels }}
    {{ toYaml .Values.extraPodlabels | nindent 4 }}
    {{- end }}
  ports:
    - name: mrp-ws-http
      port: 3001
      targetPort: wallet-port
      protocol: TCP
    - name: mrp-ws-req-http
      port: 3002
      targetPort: requester-port
      protocol: TCP
