apiVersion: v2
type: application
name: keycloak
version: 1.0.1
appVersion: "26.7.3"
description: A helm-chart for Keycloak.
dependencies:
  - name: sp-common
    repository: "file://../sp-common"
    version: 1.x.x
