apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.componentSelectorLabels" (list "server" .) | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        {{- include "common.labels.componentSelectorLabels" (list "server" .) | nindent 8 }}
        {{- if .Values.extraPodlabels }}
        {{- toYaml .Values.extraPodlabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "common.names.fullname" . }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8001
          volumeMounts:
            - name: issuance-server-settings
              mountPath: /issuance_server.toml
              subPath: issuance_server.toml
            - name: demo-issuer-metadata
              mountPath: /com.example.degree.json
              subPath: com.example.degree.json
            - name: demo-issuer-metadata
              mountPath: /com.example.insurance.json
              subPath: com.example.insurance.json
          env:
            - name: ISSUANCE_SERVER__PUBLIC_URL
              value: {{ include "common.urls.combineDomainAndContext" (list .Values.ingress.hostname .Values.ingress.contextPath) }}
            - name: ISSUANCE_SERVER__UNIVERSAL_LINK_BASE_URL
              value: {{ .Values.universalLinkBaseUrl }}
            - name: ISSUANCE_SERVER__STRUCTURED_LOGGING
              value: "true"
            - name: ISSUANCE_SERVER__METADATA
              value: "com.example.degree.json,com.example.insurance.json"
            - name: ISSUANCE_SERVER__STORAGE__URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: url
            - name: ISSUANCE_SERVER__ISSUER_TRUST_ANCHORS
              valueFrom:
                configMapKeyRef:
                  name: nl-wallet-server-trust-anchors
                  key: issuer_trust_anchors
            - name: ISSUANCE_SERVER__READER_TRUST_ANCHORS
              valueFrom:
                configMapKeyRef:
                  name: nl-wallet-server-trust-anchors
                  key: reader_trust_anchors
            - name: RUST_LOG
              value: "debug,hyper=warn"
      volumes:
        - name: issuance-server-settings
          secret:
            secretName: nl-wallet-demo-issuer-issuance-server-settings
        - name: demo-issuer-metadata
          configMap:
            name: nl-wallet-demo-issuer-metadata
