## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
## @section Global parameters
## @param global.imageRegistry Global Docker image registry
##
global:
  imageRegistry: ""

## @section Image parameters
## @param image.repository Repository for the container image
## @param image.pullPolicy Image pull policy
## @param image.tag Image tag
##
image:
  repository: null
  pullPolicy: IfNotPresent
  tag: null

## @section Image preload parameters
## Parameters for the preload container image
## @param imagePreload.repository Repository for the preload container image
## @param imagePreload.pullPolicy Image pull policy for the preload container
##
imagePreload:
  repository: null
  pullPolicy: IfNotPresent

## @section Image GBA Frontend parameters
## Parameters for the GBA Frontend container image
## @param imageGbaFrontend.repository Repository for the GBA Frontend container image
## @param imageGbaFrontend.pullPolicy Image pull policy for the GBA Frontend container
##
imageGbaFrontend:
  repository: null
  pullPolicy: IfNotPresent

## @section Image pull secrets
## Secrets for pulling images from private registries
## @param imagePullSecrets Array of secret names for private registries
##
imagePullSecrets: []

## @section Service account name
## Name of the service account to use
## @param serviceAccountName Name of the service account
##
serviceAccountName: null

## @section Security context
## Security context for the containers
## @param securityContext Security context for the containers
##
securityContext: {}

## @section Network Policy configuration
## Parameters for the network policy configuration
## @param networkPolicy.ingress Ingress rules for GBA converter pods pods
##
networkPolicy:
  ingress: []

## @section GBA HC Converter parameters
## Parameters for the GBA HC Converter configuration
## @param gbaHcConverter.replicaCount Number of replicas for the GBA HC Converter
## @param gbaHcConverter.extraPodlabels Additional labels for the pods
## @param gbaHcConverter.runMode Run mode for the GBA HC Converter (e.g., ALL, PRELOADED, GBAV)
## @param gbaHcConverter.envVarNamePreloaded Environment variable name for the preloaded run mode
## @param gbaHcConverter.envVarNameGbav Environment variable name for the GBAV run mode
## @param gbaHcConverter.preloadedXmlPath Path to the preloaded XML files
## @param gbaHcConverter.resources.requests.cpu CPU request
## @param gbaHcConverter.resources.requests.memory Memory request
## @param gbaHcConverter.resources.limits.cpu CPU limit
## @param gbaHcConverter.resources.limits.memory Memory limit
gbaHcConverter:
  replicaCount: 2
  extraPodlabels: {}
  runMode: ALL
  envVarNamePreloaded: ALL__PRELOADED
  envVarNameGbav: ALL__GBAV
  preloadedXmlPath: "resources/encrypted-gba-v-responses"
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

## @section GBA CLI Tool parameters
## Parameters for the GBA CLI Tool configuration
## @param gbaCliTool.enabled Enable or disable the GBA CLI Tool
## @param gbaCliTool.useRijksweb Enable or disable the use of Rijksweb proxy
##
gbaCliTool:
  enabled: false
  useRijksweb: false

## @section GBA Encrypt Test Data parameters
## Parameters for the GBA Encrypt Test Data configuration
## @param gbaEncryptTestData.name Name of the GBA Encrypt Test Data cronjob
## @param gbaEncryptTestData.enabled Enable or disable the GBA Encrypt Test Data
## @param gbaEncryptTestData.extraPodlabels Additional labels for the GBA Encrypt Test Data pods
##
gbaEncryptTestData:
  name: encrypt-gba-v-testdata
  enabled: false
  extraPodlabels: {}

## @section Host Aliases
## Host aliases for the containers
## @param hostAliases List of host aliases
##
hostAliases: []

## @section Frontend parameters
## Parameters for the GBA Fetch frontend configuration
## @param frontend.replicaCount Number of replicas for the GBA Fetch frontend
## @param frontend.name Name of the GBA Fetch frontend application
## @param frontend.extraPodlabels Additional labels for the frontend pods
## @param frontend.ingress.className Ingress class name for the frontend
## @param frontend.ingress.hostname Ingress hostname for the frontend
## @param frontend.ingress.tlsSecretName Secret name for the ingress TLS configuration
## @param frontend.resources.requests.cpu CPU request for the frontend container
## @param frontend.resources.requests.memory Memory request for the frontend container
## @param frontend.resources.limits.cpu CPU limit for the frontend container
## @param frontend.resources.limits.memory Memory limit for the frontend container
frontend:
  replicaCount: 1
  name: gba-fetch-frontend
  extraPodlabels: {}
  ingress:
    className: nginx
    hostname: null
    tlsSecretName: null
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

## @section Preload GBA Pod parameters
## Parameters for the Preload GBA Pod configuration
## @param preloadGbaPod.name Name of the Preload GBA Pod
## @param preloadGbaPod.extraPodlabels Additional labels for the Preload GBA Pod
preloadGbaPod:
  name: preload-gba-v-data-pod
  extraPodlabels: {}
