[package]
name = "demo_index"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
askama.workspace = true
askama_web = { workspace = true, features = ["axum-0.8"] }
axum = { workspace = true, features = ["http1", "query", "tokio", "tower-log", "tracing", "macros"] }
config = { workspace = true, features = ["preserve_order", "toml"] }
itertools.workspace = true
serde = { workspace = true, features = ["derive"] }
strum.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tower.workspace = true
tower-http = { workspace = true, features = ["fs", "trace"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = [
    "std",
    "fmt",
    "tracing-log",
    "smallvec",
    "parking_lot",
    "env-filter",
    "json",
    "ansi",
] }
url = { workspace = true, features = ["serde"] }

demo_utils.path = "../demo_utils"
http_utils.path = "../../lib/http_utils"
utils.path = "../../lib/utils"
