// Mocks generated by Mockito 5.4.2 from annotations
// in wallet/test/src/mocks/wallet_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:wallet/bridge_generated.dart' as _i2;
import 'package:wallet/src/data/repository/pid/pid_repository.dart' as _i3;
import 'package:wallet/src/data/repository/wallet/wallet_repository.dart' as _i6;
import 'package:wallet/src/domain/model/navigation/navigation_request.dart' as _i11;
import 'package:wallet/src/domain/model/pid/pid_issuance_status.dart' as _i5;
import 'package:wallet/src/domain/usecase/deeplink/decode_deeplink_usecase.dart' as _i10;
import 'package:wallet/src/domain/usecase/network/check_has_internet_usecase.dart' as _i16;
import 'package:wallet/src/domain/usecase/pid/update_pid_issuance_status_usecase.dart' as _i12;
import 'package:wallet/src/domain/usecase/pin/unlock_wallet_with_pin_usecase.dart' as _i7;
import 'package:wallet/src/domain/usecase/wallet/is_wallet_initialized_with_pid_usecase.dart' as _i13;
import 'package:wallet/src/domain/usecase/wallet/observe_wallet_lock_usecase.dart' as _i14;
import 'package:wallet/src/domain/usecase/wallet/setup_mocked_wallet_usecase.dart' as _i15;
import 'package:wallet/src/wallet_core/typed_wallet_core.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWalletUnlockResult_0 extends _i1.SmartFake implements _i2.WalletUnlockResult {
  _FakeWalletUnlockResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PidRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPidRepository extends _i1.Mock implements _i3.PidRepository {
  @override
  _i4.Future<String> getPidIssuanceUrl() => (super.noSuchMethod(
        Invocation.method(
          #getPidIssuanceUrl,
          [],
        ),
        returnValue: _i4.Future<String>.value(''),
        returnValueForMissingStub: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);
  @override
  _i4.Future<void> cancelPidIssuance() => (super.noSuchMethod(
        Invocation.method(
          #cancelPidIssuance,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  void notifyPidIssuanceStateUpdate(_i2.PidIssuanceEvent? event) => super.noSuchMethod(
        Invocation.method(
          #notifyPidIssuanceStateUpdate,
          [event],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Stream<_i5.PidIssuanceStatus> observePidIssuanceStatus() => (super.noSuchMethod(
        Invocation.method(
          #observePidIssuanceStatus,
          [],
        ),
        returnValue: _i4.Stream<_i5.PidIssuanceStatus>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.PidIssuanceStatus>.empty(),
      ) as _i4.Stream<_i5.PidIssuanceStatus>);
}

/// A class which mocks [WalletRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletRepository extends _i1.Mock implements _i6.WalletRepository {
  @override
  _i4.Stream<bool> get isLockedStream => (super.noSuchMethod(
        Invocation.getter(#isLockedStream),
        returnValue: _i4.Stream<bool>.empty(),
        returnValueForMissingStub: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);
  @override
  _i4.Future<void> validatePin(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #validatePin,
          [pin],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> createWallet(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #createWallet,
          [pin],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<bool> isRegistered() => (super.noSuchMethod(
        Invocation.method(
          #isRegistered,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<void> destroyWallet() => (super.noSuchMethod(
        Invocation.method(
          #destroyWallet,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i2.WalletUnlockResult> unlockWallet(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #unlockWallet,
          [pin],
        ),
        returnValue: _i4.Future<_i2.WalletUnlockResult>.value(_FakeWalletUnlockResult_0(
          this,
          Invocation.method(
            #unlockWallet,
            [pin],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.WalletUnlockResult>.value(_FakeWalletUnlockResult_0(
          this,
          Invocation.method(
            #unlockWallet,
            [pin],
          ),
        )),
      ) as _i4.Future<_i2.WalletUnlockResult>);
  @override
  void lockWallet() => super.noSuchMethod(
        Invocation.method(
          #lockWallet,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<_i7.CheckPinResult> confirmTransaction(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #confirmTransaction,
          [pin],
        ),
        returnValue: _i4.Future<_i7.CheckPinResult>.value(_i8.dummyValue<_i7.CheckPinResult>(
          this,
          Invocation.method(
            #confirmTransaction,
            [pin],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i7.CheckPinResult>.value(_i8.dummyValue<_i7.CheckPinResult>(
          this,
          Invocation.method(
            #confirmTransaction,
            [pin],
          ),
        )),
      ) as _i4.Future<_i7.CheckPinResult>);
}

/// A class which mocks [TypedWalletCore].
///
/// See the documentation for Mockito's code generation for more information.
class MockTypedWalletCore extends _i1.Mock implements _i9.TypedWalletCore {
  @override
  _i4.Stream<bool> get isLocked => (super.noSuchMethod(
        Invocation.getter(#isLocked),
        returnValue: _i4.Stream<bool>.empty(),
        returnValueForMissingStub: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);
  @override
  _i4.Future<_i2.PinValidationResult> isValidPin(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #isValidPin,
          [pin],
        ),
        returnValue: _i4.Future<_i2.PinValidationResult>.value(_i2.PinValidationResult.Ok),
        returnValueForMissingStub: _i4.Future<_i2.PinValidationResult>.value(_i2.PinValidationResult.Ok),
      ) as _i4.Future<_i2.PinValidationResult>);
  @override
  _i4.Future<void> register(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #register,
          [pin],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<bool> isRegistered() => (super.noSuchMethod(
        Invocation.method(
          #isRegistered,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<void> lockWallet() => (super.noSuchMethod(
        Invocation.method(
          #lockWallet,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<_i2.WalletUnlockResult> unlockWallet(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #unlockWallet,
          [pin],
        ),
        returnValue: _i4.Future<_i2.WalletUnlockResult>.value(_FakeWalletUnlockResult_0(
          this,
          Invocation.method(
            #unlockWallet,
            [pin],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.WalletUnlockResult>.value(_FakeWalletUnlockResult_0(
          this,
          Invocation.method(
            #unlockWallet,
            [pin],
          ),
        )),
      ) as _i4.Future<_i2.WalletUnlockResult>);
  @override
  _i4.Future<String> createPidIssuanceRedirectUri() => (super.noSuchMethod(
        Invocation.method(
          #createPidIssuanceRedirectUri,
          [],
        ),
        returnValue: _i4.Future<String>.value(''),
        returnValueForMissingStub: _i4.Future<String>.value(''),
      ) as _i4.Future<String>);
  @override
  _i4.Stream<_i2.ProcessUriEvent> processUri(Uri? uri) => (super.noSuchMethod(
        Invocation.method(
          #processUri,
          [uri],
        ),
        returnValue: _i4.Stream<_i2.ProcessUriEvent>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.ProcessUriEvent>.empty(),
      ) as _i4.Stream<_i2.ProcessUriEvent>);
  @override
  _i4.Future<void> cancelPidIssuance() => (super.noSuchMethod(
        Invocation.method(
          #cancelPidIssuance,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Stream<_i2.FlutterConfiguration> observeConfig() => (super.noSuchMethod(
        Invocation.method(
          #observeConfig,
          [],
        ),
        returnValue: _i4.Stream<_i2.FlutterConfiguration>.empty(),
        returnValueForMissingStub: _i4.Stream<_i2.FlutterConfiguration>.empty(),
      ) as _i4.Stream<_i2.FlutterConfiguration>);
}

/// A class which mocks [DecodeDeeplinkUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDecodeDeeplinkUseCase extends _i1.Mock implements _i10.DecodeDeeplinkUseCase {
  @override
  String get deeplinkHost => (super.noSuchMethod(
        Invocation.getter(#deeplinkHost),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get deepDiveHost => (super.noSuchMethod(
        Invocation.getter(#deepDiveHost),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i11.NavigationRequest? invoke(Uri? uri) => (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [uri],
        ),
        returnValueForMissingStub: null,
      ) as _i11.NavigationRequest?);
}

/// A class which mocks [UpdatePidIssuanceStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatePidIssuanceStatusUseCase extends _i1.Mock implements _i12.UpdatePidIssuanceStatusUseCase {
  @override
  _i4.Future<void> invoke(_i2.PidIssuanceEvent? state) => (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [state],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [IsWalletInitializedWithPidUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsWalletInitializedWithPidUseCase extends _i1.Mock implements _i13.IsWalletInitializedWithPidUseCase {
  @override
  _i4.Future<bool> invoke() => (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [ObserveWalletLockUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockObserveWalletLockUseCase extends _i1.Mock implements _i14.ObserveWalletLockUseCase {
  @override
  _i4.Stream<bool> invoke() => (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
        ),
        returnValue: _i4.Stream<bool>.empty(),
        returnValueForMissingStub: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);
}

/// A class which mocks [CheckPinUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckPinUseCase extends _i1.Mock implements _i7.CheckPinUseCase {
  @override
  _i4.Future<_i7.CheckPinResult> invoke(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [pin],
        ),
        returnValue: _i4.Future<_i7.CheckPinResult>.value(_i8.dummyValue<_i7.CheckPinResult>(
          this,
          Invocation.method(
            #invoke,
            [pin],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i7.CheckPinResult>.value(_i8.dummyValue<_i7.CheckPinResult>(
          this,
          Invocation.method(
            #invoke,
            [pin],
          ),
        )),
      ) as _i4.Future<_i7.CheckPinResult>);
}

/// A class which mocks [SetupMockedWalletUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetupMockedWalletUseCase extends _i1.Mock implements _i15.SetupMockedWalletUseCase {
  @override
  _i4.Future<void> invoke() => (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [CheckHasInternetUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckHasInternetUseCase extends _i1.Mock implements _i16.CheckHasInternetUseCase {
  @override
  _i4.Future<bool> invoke() => (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
