# This component library YAML file is included
# by the public and private OpenAP documents.
components:
  schemas:
    session_request:
      description: A session request post body
      type: object
      properties:
        usecase:
          type: string
        dcql_query:
          $ref: '#/components/schemas/Query'
        return_url_template:
          type: string
          format: uri
      required:
        - usecase
        - dcql_query
        - return_url_template

    Query:
      type: object
      required:
        - credentials
      properties:
        credentials:
          type: array
          items:
            $ref: '#/components/schemas/CredentialQuery'

    CredentialQuery:
      type: object
      required:
        - id
        - format
        - meta
      properties:
        id:
          type: string
          pattern: '^[A-Za-z0-9_-]+$'
        format:
          type: string
          description: Credential format identifier (e.g. sd+sd-jwt, mso_mdoc)
        meta:
          oneOf:
            - $ref: '#/components/schemas/MsoMdocMeta'
            - $ref: '#/components/schemas/SdJwtMeta'
        claims:
          type: array
          items:
            $ref: '#/components/schemas/ClaimsQuery'

    ClaimsQuery:
      type: object
      required:
        - path
      properties:
        id:
          type: string
        path:
          $ref: '#/components/schemas/ClaimPath'
        intent_to_retain:
          type: boolean

    ClaimPath:
      type: array
      items:
        oneOf:
          - type: string
          - type: integer
            minimum: 0
          - type: 'null'

    MsoMdocMeta:
      type: object
      description: Metadata for mso_mdoc format
      properties:
        doctype_value:
          type: string
          description: Value for the ISO-compliant mdoc document type
      required:
        - doctype_value

    SdJwtMeta:
      type: object
      description: Metadata for sd+sd-jwt format
      properties:
        vct_values:
          type: array
          description: Values for the credential type (vct) claim
          items:
            type: string
      required:
        - vct_values

    session_token:
      description: The unique identifier of a session
      type: string
      minLength: 32
      maxLength: 32
      pattern: '^[a-zA-Z0-9]{32}$'

    session_type:
      description: The type of the session
      type: string
      enum:
        - cross_device
        - same_device

    session_status:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
          - CREATED
          - WAITING_FOR_RESPONSE
          - DONE
          - FAILED
          - CANCELLED
          - EXPIRED
        ul:
          type: string
          format: uri

    token_response:
      description: An object containing a session token
      type: object
      required:
        - session_token
      properties:
        session_token:
          $ref: '#/components/schemas/session_token'

    disclosed_attributes:
      description: An array with the resultant disclosed attributes
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          attestations:
            type: array
            items:
              $ref: '#/components/schemas/disclosed_attestation'
        required:
          - id
          - attestations

    disclosed_attestation:
      type: object
      properties:
        attestation_type: string
        attributes:
          $ref: '#/components/schemas/attributes'
        issuer:
          type: string
        ca:
          type: string
        validity_info:
          $ref: '#/components/schemas/validity_info'
      required:
        - attributes
        - issuer
        - validity_info

    attributes:
      type: object
      additionalProperties: true
      example:
        attributeName: attributeValue

    validity_info:
      type: object
      properties:
        signed:
          type: string
          format: date-time
        valid_from:
          type: string
          format: date-time
        valid_until:
          type: string
          format: date-time
      required:
        - signed
        - valid_from
        - valid_until

    error_message:
      type: object
      required:
        - type
        - title
        - status
        - detail
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: int
        detail:
          type string

    ephemeral_id:
      description: An ephemeral id
      type: string

    time:
      description: Time in RFC 3339 format
      type: string
      format: date-time

    wallet_nonce:
      description: A cryptographic nonce
      type: object
      required:
        - wallet_nonce
      properties:
        wallet_nonce: string

    vp_token:
      description: A verifiable presentation token
      type: object
      required:
        - vp_token
      properties:
        vp_token: string

    redirect_object:
      description: A redirect object
      type: object
      required:
        - redirect_uri
      properties:
        redirect_uri:
          type: string
          format: uri

    oauth_authz_data:
      description: Oauth authz data
      type: string
