use chrono::Utc;
use sea_orm::ActiveModelTrait;
use sea_orm::ActiveValue;
use sea_orm::ColumnTrait;
use sea_orm::DatabaseConnection;
use sea_orm::DbErr;
use sea_orm::EntityTrait;
use sea_orm::QueryFilter;
use sea_orm::SqlErr;

use openid4vc::nonce_store::MemoryNonceStore;
use openid4vc::nonce_store::MemoryNonceStoreError;
use openid4vc::nonce_store::NonceStore;
use server_utils::store::StoreConnection;

use crate::entity::prelude::*;
use crate::entity::proof_nonce;

#[derive(Debug, thiserror::Error)]
pub enum ProofNonceStoreError {
    #[error("nonce is already present: {0}")]
    DuplicateNonce(String),

    #[error("could not store nonce in database: {0}")]
    DbInsertNonce(#[source] DbErr),

    #[error("could not find and delete nonce from database: {0}")]
    DbDeleteNonce(#[source] DbErr),
}

impl From<MemoryNonceStoreError> for ProofNonceStoreError {
    fn from(value: MemoryNonceStoreError) -> Self {
        match value {
            MemoryNonceStoreError::DuplicateNonce(nonce) => Self::DuplicateNonce(nonce),
        }
    }
}

#[derive(Debug)]
enum NonceStoreBackend {
    Postgres(DatabaseConnection),
    Memory(MemoryNonceStore),
}

/// Stores nonces generated by the issuer nonce endpoint either in PostgreSQL or in memory.
#[derive(Debug)]
pub struct ProofNonceStore {
    backend: NonceStoreBackend,
}

impl ProofNonceStore {
    pub fn new(store_connection: StoreConnection) -> Self {
        let backend = match store_connection {
            StoreConnection::Postgres(connection) => NonceStoreBackend::Postgres(connection),
            StoreConnection::Memory => NonceStoreBackend::Memory(MemoryNonceStore::default()),
        };

        Self { backend }
    }
}

impl NonceStore for ProofNonceStore {
    type Error = ProofNonceStoreError;

    async fn store_nonce(&self, nonce: String) -> Result<(), Self::Error> {
        match &self.backend {
            NonceStoreBackend::Postgres(connection) => {
                proof_nonce::ActiveModel {
                    id: ActiveValue::NotSet,
                    nonce: ActiveValue::Set(nonce.clone()),
                    created_date_time: ActiveValue::Set(Utc::now().into()),
                }
                .insert(connection)
                .await
                .map_err(|error| {
                    // Return a specific error variant only if the nonce already exists in the database.
                    error
                        .sql_err()
                        .and_then(|sql_error| {
                            matches!(sql_error, SqlErr::UniqueConstraintViolation(_))
                                .then_some(ProofNonceStoreError::DuplicateNonce(nonce))
                        })
                        .unwrap_or(ProofNonceStoreError::DbInsertNonce(error))
                })?;
            }
            NonceStoreBackend::Memory(memory_store) => {
                memory_store.store_nonce(nonce).await?;
            }
        }

        Ok(())
    }

    async fn find_and_remove_nonce(&self, nonce: &str) -> Result<bool, Self::Error> {
        let had_nonce = match &self.backend {
            NonceStoreBackend::Postgres(connection) => {
                let delete_result = ProofNonce::delete_many()
                    .filter(proof_nonce::Column::Nonce.eq(nonce))
                    .exec(connection)
                    .await
                    .map_err(ProofNonceStoreError::DbDeleteNonce)?;

                delete_result.rows_affected > 0
            }
            NonceStoreBackend::Memory(memory_store) => memory_store.find_and_remove_nonce(nonce).await?,
        };

        Ok(had_nonce)
    }
}
