use chrono::DateTime;
use chrono::Utc;
use itertools::Itertools;
use jwt::nonce::Nonce;
use openid4vc::nonce::C_NONCE_VALIDITY;
use openid4vc::nonce::memory_store::MemoryNonceStore;
use openid4vc::nonce::memory_store::NonceStoreResult;
use openid4vc::nonce::store::NonceStatus;
use openid4vc::nonce::store::NonceStore;
use openid4vc::nonce::store::NonceStoreError;
use sea_orm::ActiveModelTrait;
use sea_orm::ActiveValue;
use sea_orm::ColumnTrait;
use sea_orm::DatabaseConnection;
use sea_orm::DbErr;
use sea_orm::EntityTrait;
use sea_orm::QueryFilter;
use sea_orm::SqlErr;
use server_utils::store::StoreConnection;
use utils::generator::Generator;
use utils::generator::TimeGenerator;

use crate::entity::prelude::*;
use crate::entity::proof_nonce;

#[derive(Debug, thiserror::Error)]
pub enum ProofNonceStoreError {
    #[error("could not store nonce in database: {0}")]
    DbInsertNonce(#[source] DbErr),

    #[error("could not find and delete nonce from database: {0}")]
    DbDeleteNonce(#[source] DbErr),
}

#[derive(Debug)]
enum NonceStoreBackend {
    Postgres(DatabaseConnection),
    Memory(MemoryNonceStore),
}

/// Stores nonces generated by the issuer nonce endpoint either in PostgreSQL or in memory.
#[derive(Debug)]
pub struct ProofNonceStore<T = TimeGenerator> {
    backend: NonceStoreBackend,
    time_generator: T,
}

impl ProofNonceStore {
    pub fn new(store_connection: StoreConnection) -> Self {
        let backend = match store_connection {
            StoreConnection::Postgres(connection) => NonceStoreBackend::Postgres(connection),
            StoreConnection::Memory => NonceStoreBackend::Memory(MemoryNonceStore::new()),
        };

        Self {
            backend,
            time_generator: TimeGenerator,
        }
    }
}

#[cfg(feature = "db_test")]
impl<T> ProofNonceStore<T>
where
    T: Clone,
{
    pub fn new_postgres_with_time_generator(database_connection: DatabaseConnection, time_generator: T) -> Self {
        Self {
            backend: NonceStoreBackend::Postgres(database_connection),
            time_generator,
        }
    }
}

impl<T> ProofNonceStore<T>
where
    T: Generator<DateTime<Utc>>,
{
    fn now(&self) -> DateTime<Utc> {
        self.time_generator.generate()
    }
}

impl<T> NonceStore for ProofNonceStore<T>
where
    T: Generator<DateTime<Utc>> + Send + Sync,
{
    type Error = ProofNonceStoreError;

    async fn store_nonce(&self, nonce: Nonce) -> Result<(), NonceStoreError<Self::Error>> {
        match &self.backend {
            NonceStoreBackend::Postgres(connection) => {
                proof_nonce::ActiveModel {
                    id: ActiveValue::NotSet,
                    nonce: ActiveValue::Set(String::from(nonce.clone())),
                    created_date_time: ActiveValue::Set(self.now().into()),
                }
                .insert(connection)
                .await
                .map_err(|error| {
                    // Return a specific error variant only if the nonce already exists in the database.
                    error
                        .sql_err()
                        .and_then(|sql_error| {
                            matches!(sql_error, SqlErr::UniqueConstraintViolation(_))
                                .then_some(NonceStoreError::DuplicateNonce(nonce))
                        })
                        .unwrap_or(ProofNonceStoreError::DbInsertNonce(error).into())
                })?;

                Ok(())
            }
            NonceStoreBackend::Memory(memory_store) => match memory_store.store(nonce.clone()) {
                NonceStoreResult::Stored => Ok(()),
                NonceStoreResult::DuplicateEntry => Err(NonceStoreError::DuplicateNonce(nonce)),
            },
        }
    }

    async fn check_nonce_status_and_remove<'a>(
        &self,
        nonces: impl IntoIterator<Item = &'a Nonce> + Send,
    ) -> Result<NonceStatus, Self::Error> {
        let status = match &self.backend {
            NonceStoreBackend::Postgres(connection) => {
                let nonces = nonces.into_iter().map(Nonce::as_ref).unique().collect_vec();
                let nonce_count = nonces.len();

                let deleted_nonces = ProofNonce::delete_many()
                    .filter(proof_nonce::Column::Nonce.is_in(nonces))
                    .exec_with_returning(connection)
                    .await
                    .map_err(ProofNonceStoreError::DbDeleteNonce)?;

                match deleted_nonces.len() {
                    deleted_nonce_count if deleted_nonce_count > nonce_count => {
                        panic!(
                            "database deleted more nonces than requested, this should not happen as the nonce column \
                             is unique"
                        )
                    }
                    deleted_nonce_count
                        if deleted_nonce_count == nonce_count
                            && deleted_nonces
                                .into_iter()
                                .all(|nonce| nonce.created_date_time + C_NONCE_VALIDITY >= self.now()) =>
                    {
                        NonceStatus::AllValid
                    }
                    // deleted_nonce_count < nonce_count
                    _ => NonceStatus::AtLeastOneAbsentOrExpired,
                }
            }
            NonceStoreBackend::Memory(memory_store) => memory_store.remove_and_check(nonces),
        };

        Ok(status)
    }
}
