services:
  postgres:
    container_name: postgres
    image: docker.io/library/postgres
    environment:
      # POSTGRES_HOST_AUTH_METHOD=trust is recommended only for development.
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    network_mode: bridge
    volumes:
      - postgres:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d

  brpproxy:
    container_name: brpproxy
    image: ghcr.io/brp-api/haal-centraal-brp-bevragen-proxy:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5000
      - Routes__0__DownstreamScheme=http
      - Routes__0__DownstreamHostAndPorts__0__Host=docker-host
      - Routes__0__DownstreamHostAndPorts__0__Port=${GBA_HC_CONV_PORT}
    ports:
      - "${BRP_SERVER_PORT}:5000"
    network_mode: bridge
    extra_hosts:
      - "docker-host:${DOCKER_HOST_GATEWAY:-host-gateway}"

  gbamock:
    container_name: gbamock
    image: ghcr.io/brp-api/haal-centraal-brp-bevragen-gba-mock:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010
    ports:
      - "${GBA_HC_MOCK_PORT}:5010"
    network_mode: bridge

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_PASSWORD}
      - KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/data/certs/keycloak.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/data/certs/keycloak.key
    ports:
      - "${KC_PORT_HTTP}:8080"
      - "${KC_PORT_HTTPS}:8443"
    network_mode: bridge
    volumes:
      - keycloak:/opt/keycloak/data
    command:
      - start-dev

networks:
  default:
    external: true
    name: bridge

volumes:
  postgres:
    name: postgres
  keycloak:
    name: keycloak
