services:
  postgres:
    container_name: postgres
    image: docker.io/bitnami/postgresql
    ports:
      - "5432:5432"
    network_mode: bridge
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
    volumes:
      - postgres:/bitnami/postgresql
      - postgres:/docker-entrypoint-initdb.d
      - postgres:/docker-entrypoint-preinitdb.d
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  brpproxy:
    container_name: brpproxy
    image: ghcr.io/brp-api/haal-centraal-brp-bevragen-proxy:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:3011
      - Routes__0__DownstreamScheme=http
      - Routes__0__DownstreamHostAndPorts__0__Host=docker-host
      - Routes__0__DownstreamHostAndPorts__0__Port=${GBA_HC_CONV_PORT}
    ports:
      - "${BRP_SERVER_PORT}:3011"
    network_mode: bridge
    extra_hosts:
      - "docker-host:host-gateway"

  gbamock:
    container_name: gbamock
    image: ghcr.io/brp-api/haal-centraal-brp-bevragen-gba-mock:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010
    ports:
      - "5010:5010"
    network_mode: bridge

networks:
  default:
    external: true
    name: bridge

volumes:
  postgres:
    name: postgres
