npm-audit-fix:
  image: "${HARBOR_REGISTRY}/${HARBOR_PROJECT}/nl-wallet-app-builder-ci-node:${BUILD_TAG}"
  rules:
    - !reference [.on-schedule-scan, rules]
  script:
    - scripts/npm-audit-fix.sh

cargo-audit-fix:
  image: "${HARBOR_REGISTRY}/${HARBOR_PROJECT}/nl-wallet-app-builder-ci-rust:${BUILD_TAG}"
  tags:
    - linux
  rules:
    - !reference [.on-schedule-scan, rules]
  script:
    - scripts/cargo-audit-fix.sh

pip-audit-fix:
  tags:
    - linux
  rules:
    - !reference [.on-schedule-scan, rules]
  script:
    - scripts/pip-audit-fix.sh
