browsertests-format-lint:
  rules: !reference [.default-or-merge-request, rules]
  image: "${HARBOR_REGISTRY}/${HARBOR_PROJECT}/nl-wallet-app-builder-ci-node:${BUILD_TAG}"
  script:
    - cd browsertests
    - pnpm install --frozen-lockfile
    - pnpm run format-check
    - pnpm run lint

.run-browsertest-common:
  image: "${HARBOR_REGISTRY}/${HARBOR_PROJECT}/nl-wallet-app-builder-ci-playwright:${BUILD_TAG}"
  extends: .env-k8s
  rules:
    - !reference [.default-branch, rules]
  needs:
    - job: build-env-ont
      artifacts: true
    - job: deploy-apps-ont
      artifacts: false
  before_script:
    - cd browsertests
    - pnpm install --frozen-lockfile

run-wallet-web-browsertest-test-ont:
  extends: .run-browsertest-common
  script:
    - cd packages/wallet-web
    - pnpm run test:ci
  after_script:
    - deploy/bin/store-artifact.sh browsertests/packages/wallet-web/test-results/results.xml
      qt/quality-time/junit-results/browsertest-wallet-web.xml
    - deploy/bin/store-artifact-zip.sh qt/quality-time/allure-results/browsertest-wallet-web.zip
      browsertests/packages/wallet-web/allure-results/*
  artifacts:
    name: browsertest-wallet-web
    when: always
    paths:
      - browsertests/packages/wallet-web/test-results/
      - browsertests/packages/wallet-web/allure-results/
    reports:
      junit: browsertests/packages/wallet-web/test-results/*.xml

run-fallback-pages-browsertest-test-ont:
  extends: .run-browsertest-common
  script:
    - cd packages/fallback-pages
    - pnpm run test:ci
  after_script:
    - deploy/bin/store-artifact.sh browsertests/packages/fallback-pages/test-results/results.xml
      qt/quality-time/junit-results/browsertest-fallback-pages.xml
    - deploy/bin/store-artifact-zip.sh qt/quality-time/allure-results/browsertest-fallback-pages.zip
      browsertests/packages/fallback-pages/allure-results/*
  artifacts:
    name: browsertest-fallback-page
    when: always
    paths:
      - browsertests/packages/fallback-pages/test-results/
      - browsertests/packages/fallback-pages/allure-results/
    reports:
      junit: browsertests/packages/fallback-pages/test-results/*.xml

run-revocation-portal-browsertest-test-ont:
  extends: .run-browsertest-common
  script:
    - cd packages/revocation-portal
    - pnpm run test:ci
  after_script:
    - deploy/bin/store-artifact.sh browsertests/packages/revocation-portal/test-results/results.xml
      qt/quality-time/junit-results/browsertest-revocation-portal.xml
    - deploy/bin/store-artifact-zip.sh qt/quality-time/allure-results/browsertest-revocation-portal.zip
      browsertests/packages/revocation-portal/allure-results/*
  artifacts:
    name: browsertest-revocation-portal
    when: always
    paths:
      - browsertests/packages/revocation-portal/test-results/
      - browsertests/packages/revocation-portal/allure-results/
    reports:
      junit: browsertests/packages/revocation-portal/test-results/*.xml

run-digid-bridge-test-ont:
  extends:
    - .test-rust
    - .env-k8s
  rules: !reference [.default-or-merge-request-manual, rules]
  needs:
    - job: build-env-ont
      artifacts: true
  variables:
    SKIP_DIGID_CONNECTOR: "true"
    SKIP_WALLET_WEB: "true"
    SKIP_KEYCLOAK: "true"
    DB_HOST: "postgres"
  services:
    - name: "${HARBOR_REGISTRY}/${HARBOR_PROJECT}/nl-wallet-app-builder-postgres:${BUILD_TAG}"
      alias: postgres
      command: [
          "postgres",
          # Allow for more connections with larger shared buffers
          "-N",
          "768",
          "-c",
          "shared_buffers=128MB",
          # Use non-durable settings: https://www.postgresql.org/docs/current/non-durability.html
          "-c",
          "fsync=off",
          "-c",
          "synchronous_commit=off",
          "-c",
          "full_page_writes=off",
          # Minimal WAL
          "-c",
          "wal_level=minimal",
          "-c",
          "max_wal_senders=0",
        ]
      variables:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
  before_script:
    - set -euo pipefail
    - PID_ISSUER__DIGID__BSN_PRIVKEY="$(kubectl get secret nl-wallet-pid-issuer-digid-bsn-privkey --output=jsonpath='{.data.bsn_privkey}' | base64 --decode)"
    - export PID_ISSUER__DIGID__BSN_PRIVKEY
    - PID_ISSUER__DIGID__CLIENT_SETTINGS__TRUST_ANCHORS="$(kubectl get configmap nl-wallet-pid-issuer-digid-http-trust-anchors --output=jsonpath='{.data.trust_anchors}')"
    - export PID_ISSUER__DIGID__CLIENT_SETTINGS__TRUST_ANCHORS
    - PID_ISSUER__DIGID__CLIENT_SETTINGS__OIDC_IDENTIFIER="$DIGID_BASE_URL"
    - export PID_ISSUER__DIGID__CLIENT_SETTINGS__OIDC_IDENTIFIER
    - PID_ISSUER__DIGID__CLIENT_ID="$DIGID_CLIENT_ID"
    - export PID_ISSUER__DIGID__CLIENT_ID
    # Port-forward brpproxy (internal-only in the cluster) to localhost for the in-process pid_issuer.
    - kubectl port-forward service/brpproxy 5001:80 &
    - export PID_ISSUER__BRP_SERVER="http://localhost:5001/"
  script:
    - ./scripts/setup-devenv.sh
    - cd wallet_core
    - RUST_BACKTRACE=1 CONFIG_ENV=dev cargo nextest run --package tests_integration --test digid_issuance --features
      digid_test --locked

.run-performance-test-ont-base:
  extends: .env-k8s
  script:
    - START_TIME=$(date -u -d "-1 minute" "+%Y-%m-%d %H:%M:%S")
    - echo "Performance test starting, query range begins at $START_TIME"
    - DELAY=0.2 wallet_core/tests_integration/run_performance_test.sh --skip-build 25
    - END_TIME=$(date -u -d "+1 minute" "+%Y-%m-%d %H:%M:%S")
    - echo "Performance test completed, query range ends at $END_TIME"
    - echo "START_TIME=$START_TIME" > perf-test-timeframe.txt
    - echo "END_TIME=$END_TIME" >> perf-test-timeframe.txt
  artifacts:
    paths:
      - perf-test-timeframe.txt
    when: on_success

run-performance-test-ont-pipeline-deploy:
  extends: .run-performance-test-ont-base
  rules:
    - !reference [.default-branch, rules]
  needs:
    - job: build-performance-test
      artifacts: true
    - job: deploy-apps-ont
      artifacts: false
  allow_failure: false

run-performance-test-ont-existing-deploy:
  extends: .run-performance-test-ont-base
  rules:
    - !reference [.on-schedule-nightly-performance-test, rules]
    - !reference [.default-manual-or-merge-request-manual, rules]
  needs:
    - job: build-performance-test
      artifacts: true
  allow_failure: true

retrieve-performance-test-results-ont:
  extends: .env-k8s
  rules:
    - !reference [.on-schedule-nightly-performance-test, rules]
  needs:
    - job: run-performance-test-ont-existing-deploy
      artifacts: true
  before_script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install --no-cache-dir --upgrade pip
    - pip3 install --no-cache-dir -r deploy/qa-util/requirements.txt
  script:
    - START_TIME=$(grep START_TIME perf-test-timeframe.txt | cut -d'=' -f2-)
    - END_TIME=$(grep END_TIME perf-test-timeframe.txt | cut -d'=' -f2-)
    - echo "Using START_TIME=${START_TIME} and END_TIME=${END_TIME}"
    - |
      python3 deploy/qa-util/generate-k6-summary-from-grafana.py \
        --grafana-url "${SP_GRAFANA_TEST_API_URL}" \
        --api-token "${SP_GRAFANA_TEST_API_KEY}" \
        --start-time "$START_TIME" \
        --end-time "$END_TIME" \
        --output-file k6-summary.json
  after_script:
    - deploy/bin/store-artifact.sh k6-summary.json qt/quality-time/performance-results/k6-summary.json
  artifacts:
    paths:
      - k6-summary.json
    when: on_success
  variables:
    TESTS:

extract-manual-test-set:
  rules: !reference [.default-branch-manual, rules]
  script:
    - ./deploy/qa-util/extract-manual-test-set.sh wallet_docs/functional-design/logical-test-cases.md manual-test-set.md
  artifacts:
    name: manual-test-set
    when: always
    paths:
      - manual-test-set.md

test-android-platform-support-browserstack:
  extends: [.upload-browserstack-base]
  resource_group: automation-tests
  rules:
    - !reference [.on-schedule-automation, rules]
    - !reference [.merge-request-manual, rules]
  needs:
    - job: build-android-platform-support-browserstack
      artifacts: true
  script:
    - bundle exec fastlane android ci_test_platform_support_browserstack

test-ios-platform-support-browserstack:
  extends: [.upload-browserstack-base]
  resource_group: automation-tests
  rules:
    - !reference [.on-schedule-automation, rules]
    - !reference [.merge-request-manual, rules]
  needs:
    - job: build-ios-platform-support-browserstack
      artifacts: true
  script:
    - bundle exec fastlane ios ci_test_platform_support_browserstack
