upload-browserstack-android-app:
  extends: [.env-k8s, .ruby-cache]
  rules: !reference [.default-branch, rules]
  needs:
    - job: build-android-app-ont-profile
      artifacts: true
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  script:
    - BROWSERSTACK_USER=$(kubectl get secret nl-wallet-browserstack -o jsonpath='{.data.user}' | base64 --decode)
    - export BROWSERSTACK_USER
    - BROWSERSTACK_KEY=$(kubectl get secret nl-wallet-browserstack -o jsonpath='{.data.key}' | base64 --decode)
    - export BROWSERSTACK_KEY
    - bundle install
    - |
      bundle exec fastlane android ci_browserstack \
        application_id:"${INTERNAL_APP_IDENTIFIER}.latest" \
        version:"${CI_COMMIT_TAG#v}"
