.upload-browserstack-base:
  extends: [ .env-k8s, .ruby-cache ]
  rules: !reference [ .default-branch, rules ]
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  before_script:
    - BROWSERSTACK_USER=$(kubectl get secret nl-wallet-browserstack -o jsonpath='{.data.user}' | base64 --decode)
    - export BROWSERSTACK_USER
    - BROWSERSTACK_KEY=$(kubectl get secret nl-wallet-browserstack -o jsonpath='{.data.key}' | base64 --decode)
    - export BROWSERSTACK_KEY
    - bundle install

### Wallet app uploads to BrowserStack

upload-browserstack-android-app:
  extends: .upload-browserstack-base
  needs:
    - job: build-android-app-ont
      artifacts: true
  script:
    - |
      bundle exec fastlane android ci_browserstack \
        application_id:"${INTERNAL_APP_IDENTIFIER}.latest"

upload-browserstack-ios-app:
  extends: .upload-browserstack-base
  needs:
    - job: build-ios-app-ont
      artifacts: true
  script:
    - |
      bundle exec fastlane ios ci_browserstack \
        application_id:"${INTERNAL_APP_IDENTIFIER}.latest"

build-ios-platform-support-browserstack:
  extends: [.env-macos-runner, .ruby-cache-macos]
  rules:
  - !reference [.on-schedule-automation, rules]
  - !reference [.merge-request-manual, rules]
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  artifacts:
    name: ios-platform-support-test-artifacts
    paths:
      - wallet_core/wallet/platform_support/ios/build/IntegrationTestsRunner.zip
  script:
    - bundle install
    - bundle exec fastlane ios build_platform_support_tests

build-android-platform-support-browserstack:
  image: "${HARBOR_REGISTRY}/${HARBOR_PROJECT}/nl-wallet-app-builder-ci-android-emulator:${BUILD_TAG}"
  extends: [.ruby-cache]
  tags:
    - linux
  rules:
  - !reference [.on-schedule-automation, rules]
  - !reference [.merge-request-manual, rules]
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  artifacts:
    name: android-platform-support-test-apks
    paths:
      - wallet_core/wallet/platform_support/android/test-app/build/outputs/apk/debug/test-app-debug.apk
      - wallet_core/wallet/platform_support/android/build/outputs/apk/androidTest/debug/platform_support-debug-androidTest.apk
  script:
    - bundle install
    - bundle exec fastlane android build_platform_support_tests
