.kaniko:
  extends: .env-ont
  before_script:
    - echo $DOCKER_AUTH_CONFIG > /kaniko/.docker/config.json
  image:
    name: "$HARBOR_REGISTRY/gcr-io-proxy/kaniko-project/executor:debug"
    entrypoint: [""]

.build-docker-image:
  extends: .kaniko
  rules: !reference [.default-or-release-or-merge-request-manual, rules]
  before_script:
    - !reference [.kaniko, before_script]
    - !reference [.release-tag, before_script]
  script:
    - TAG=${RELEASE_VERSION:-latest}
    - /kaniko/executor
      --context wallet_core
      --dockerfile $DOCKER_FILE_TO_BUILD
      --build-arg BUILD_TAG=$BUILD_TAG
      --build-arg HARBOR_REGISTRY=$HARBOR_REGISTRY
      --build-arg HARBOR_NLW_PROJECT=$HARBOR_NLW_PROJECT
      --destination $HARBOR_REGISTRY/$HARBOR_NLW_PROJECT/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
      --destination $HARBOR_REGISTRY/$HARBOR_NLW_PROJECT/$DOCKER_IMAGE_NAME:$TAG

build-update-policy-server-image:
  extends: .build-docker-image
  needs:
    - job: build-update-policy-server-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/update_policy_server/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-update-policy-server

build-wallet-provider-image:
  extends: .build-docker-image
  needs:
    - job: build-wallet-provider-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/wallet_provider/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-provider

build-wp-migrations-image:
  extends: .build-docker-image
  needs:
    - job: build-wallet-provider-migrations-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/wallet_provider/migrations/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-provider-migrations

.build-docker-image-mrp:
  extends: .build-docker-image
  script:
    - TAG=${RELEASE_VERSION:-latest}
    - /kaniko/executor
      --context wallet_core
      --dockerfile $DOCKER_FILE_TO_BUILD
      --build-arg HARBOR_REGISTRY=$HARBOR_REGISTRY
      --build-arg HARBOR_NLW_PROJECT=$HARBOR_NLW_PROJECT
      --build-arg CSP_SCRIPT_MRP_BASE64="${ARG_CSP_SCRIPT_MRP_BASE64}"
      --build-arg CSP_STYLE_MRP_BASE64="${ARG_CSP_STYLE_MRP_BASE64}"
      --build-arg WALLET_WEB_FILENAME="${ARG_WALLET_WEB_FILENAME}"
      --build-arg WALLET_WEB_SHA256="${ARG_WALLET_WEB_SHA256}"
      --destination $HARBOR_REGISTRY/$HARBOR_NLW_PROJECT/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
      --destination $HARBOR_REGISTRY/$HARBOR_NLW_PROJECT/$DOCKER_IMAGE_NAME:$TAG

build-mock-relying-party-image:
  extends: .build-docker-image-mrp
  needs:
    - job: build-wallet-web
      artifacts: true
    - job: build-demo-relying-party-binary
      artifacts: true
  before_script:
    - !reference [.build-docker-image, before_script]
    - export ARG_CSP_SCRIPT_MRP_BASE64="$(cat wallet_core/mock_relying_party/hashes/csp_script_src_mrp_base64.txt)"
    - export ARG_CSP_STYLE_MRP_BASE64="$(cat wallet_core/mock_relying_party/hashes/csp_style_src_mrp_base64.txt)"
    - export ARG_WALLET_WEB_FILENAME="$(cat wallet_core/mock_relying_party/hashes/wallet_web_filename.txt)"
    - export ARG_WALLET_WEB_SHA256="$(cat wallet_core/mock_relying_party/hashes/wallet_web_sha256.txt)"
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/mock_relying_party/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-mock-relying-party

build-wallet-server-image:
  extends: .build-docker-image
  needs:
    - job: build-wallet-server-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/wallet_server/Dockerfile.wallet_server
    DOCKER_IMAGE_NAME: nl-wallet-server

build-verification-server-image:
  extends: .build-docker-image
  needs:
    - job: build-verification-server-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/wallet_server/Dockerfile.verification_server
    DOCKER_IMAGE_NAME: nl-verification-server

build-pid-issuer-image:
  extends: .build-docker-image
  needs:
    - job: build-pid-issuer-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/wallet_server/Dockerfile.pid_issuer
    DOCKER_IMAGE_NAME: nl-pid-issuer

build-ws-migrations-image:
  extends: .build-docker-image
  needs:
    - job: build-wallet-server-migrations-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/wallet_server/migrations/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-server-migrations

build-gba-hc-converter-image:
  extends: .build-docker-image
  needs:
    - job: build-gba-hc-converter-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/gba_hc_converter/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-gba-hc-converter

build-gba-fetch-image:
  extends: .build-docker-image
  needs:
    - job: build-gba-fetch-binary
      artifacts: true
    - job: build-gba-encrypt-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/gba_hc_converter/Dockerfile.gba_fetch
    DOCKER_IMAGE_NAME: nl-wallet-gba-fetch

build-gba-fetch-frontend-image:
  extends: .build-docker-image
  needs:
    - job: build-gba-fetch-frontend-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/gba_hc_converter/Dockerfile.gba_fetch_frontend
    DOCKER_IMAGE_NAME: nl-wallet-gba-fetch-frontend
