.kaniko:
  extends: .env-ont
  before_script:
    - echo $DOCKER_AUTH_CONFIG > /kaniko/.docker/config.json
  image:
    name: "$HARBOR_REGISTRY/gcr-io-proxy/kaniko-project/executor:debug"
    entrypoint: [""]

.build-docker-image:
  extends: .kaniko
  rules: !reference [.default-or-release-or-merge-request-manual, rules]
  script:
    - TAG=${CI_COMMIT_TAG:-latest}
    - /kaniko/executor
      --context wallet_core
      --dockerfile $DOCKER_FILE_TO_BUILD
      --build-arg BUILD_TAG=$BUILD_TAG
      --build-arg HARBOR_REGISTRY=$HARBOR_REGISTRY
      --build-arg HARBOR_NLW_PROJECT=$HARBOR_NLW_PROJECT
      --destination $HARBOR_REGISTRY/$HARBOR_NLW_PROJECT/$DOCKER_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
      --destination $HARBOR_REGISTRY/$HARBOR_NLW_PROJECT/$DOCKER_IMAGE_NAME:$TAG

build-update-policy-server-image:
  extends: .build-docker-image
  needs:
    - job: build-update-policy-server-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/update_policy/server/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-update-policy-server

build-wallet-provider-image:
  extends: .build-docker-image
  needs:
    - job: build-wallet-provider-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/wallet_provider/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-provider

build-wp-migrations-image:
  extends: .build-docker-image
  needs:
    - job: build-wallet-provider-migrations-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/wallet_provider/migrations/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-provider-migrations

build-demo-relying-party-image:
  extends: .build-docker-image
  needs:
    - job: build-wallet-web
      artifacts: true
    - job: build-demo-relying-party-binary
      artifacts: true
  before_script:
    - !reference [.build-docker-image, before_script]
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/demo/demo_relying_party/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-demo-relying-party

build-demo-issuer-image:
  extends: .build-docker-image
  needs:
    - job: build-wallet-web
      artifacts: true
    - job: build-demo-issuer-binary
      artifacts: true
  before_script:
    - !reference [.build-docker-image, before_script]
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/demo/demo_issuer/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-demo-issuer

build-demo-issuer-index:
  extends: .build-docker-image
  needs:
    - job: build-demo-index-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/demo/demo_index/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-demo-index

build-verification-server-image:
  extends: .build-docker-image
  needs:
    - job: build-verification-server-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/wallet_server/verification_server/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-verification-server

build-issuance-server-image:
  extends: .build-docker-image
  needs:
    - job: build-issuance-server-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/wallet_server/issuance_server/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-issuance-server

build-pid-issuer-image:
  extends: .build-docker-image
  needs:
    - job: build-pid-issuer-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/wallet_server/pid_issuer/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-pid-issuer

build-ws-migrations-image:
  extends: .build-docker-image
  needs:
    - job: build-wallet-server-migrations-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/wallet_server/server_utils/migrations/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-server-migrations

build-gba-hc-converter-image:
  extends: .build-docker-image
  needs:
    - job: build-gba-hc-converter-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/gba_hc_converter/Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-gba-hc-converter

build-gba-fetch-image:
  extends: .build-docker-image
  needs:
    - job: build-gba-fetch-binary
      artifacts: true
    - job: build-gba-encrypt-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/gba_hc_converter/gba_fetch.Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-gba-fetch

build-gba-fetch-frontend-image:
  extends: .build-docker-image
  needs:
    - job: build-gba-fetch-frontend-binary
      artifacts: true
  variables:
    DOCKER_FILE_TO_BUILD: wallet_core/gba_hc_converter/gba_fetch_frontend.Dockerfile
    DOCKER_IMAGE_NAME: nl-wallet-gba-fetch-frontend
