build-sbom:
  image: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-ci-quality:${BUILD_TAG}"
  extends: .ruby-cache
  rules: !reference [.default-branch, rules]
  script:
    ## Rust
    - cargo cyclonedx --spec-version 1.5 --manifest-path wallet_core/Cargo.toml --format json --override-filename bom
    - cargo cyclonedx --spec-version 1.5 --manifest-path wallet_core/uniffi-bindgen/Cargo.toml --format json --override-filename bom
    ## NPM
    - cd wallet_web
    - cyclonedx-npm --spec-version 1.5 --output-format json --output-file bom.json --package-lock-only
    # only keep bundled dependencies
    - jq '.components |= map(select(.properties|any(.name == "cdx:npm:package:bundled")))' bom.json > bom-bundled.json
    - mv bom-bundled.json bom.json
    - cd ..
    ## Flutter
    - (cd wallet_app && cdxgen --fail-on-error --spec-version 1.5 --type dart --output bom.json)
    ## iOS
    - bundle install
    - cd wallet_app
    - flutter pub get --enforce-lockfile
    - flutter precache --ios
    - cd ios
    - bundle exec pod install --allow-root
    - cyclonedx-cocoapods # only supports single spec version (currently 1.6)
      # Stripping Flutter 1.0.0 because 1.0.0 doesn't present any particular Flutter release
      # https://github.com/flutter/flutter/issues/154023#issuecomment-2310710611
      # https://github.com/flutter/flutter/issues/85820#issuecomment-874103549
    - >
      cyclonedx convert --output-version v1_5 --input-file bom.xml --output-format json
      | jq 'del(.components[] | select(."bom-ref" == "pkg:cocoapods/Flutter@1.0.0?file_name=Flutter")) | del(.dependencies[].dependsOn[]? | select(. == "pkg:cocoapods/Flutter@1.0.0?file_name=Flutter"))'
      > bom.json
    - cd ../..
    ## Android
    - (cd wallet_app/android/app && GRADLE_CMD="../gradlew" cdxgen --fail-on-error --spec-version 1.5 --type gradle --output bom.json)
    - (cd wallet_core/platform_support/android && GRADLE_CMD="../gradlew" cdxgen --fail-on-error --spec-version 1.5 --type gradle --output bom.json)
    # merge sboms into one (this doesn't work when using XML, because the cdxgen bom.xml is invalid)
    - cyclonedx merge --output-version v1_5 --input-files $(find . -name bom.json) --output-file bom.json
    # converting it to xml does work
    - cyclonedx convert --output-version v1_5 --input-file bom.json --output-file bom.xml
    - deploy/bin/store-artifact.sh bom.* qt/quality-time/sbom/
  variables:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
  artifacts:
    name: sbom
    when: always
    reports:
      cyclonedx: bom.json
    paths:
      - bom.xml
      - bom.json
  allow_failure: true

upload-sbom-to-dependency-track:
  image: "${HARBOR_REGISTRY}/${HARBOR_NLW_PROJECT}/nl-wallet-app-builder-ci-quality:${BUILD_TAG}"
  extends: .env-ont-k8s
  rules: !reference [.default-branch, rules]
  needs:
    - job: build-sbom
      artifacts: true
  script: |
    # Define variables
    BOM_FILENAME="bom.json"
    API_KEY=$(kubectl get secret nl-wallet-dependency-track-secret -o jsonpath='{.data.api_key}' | base64 --decode)
    PROJECT_ID=$(kubectl get secret nl-wallet-dependency-track-secret -o jsonpath='{.data.project_id}' | base64 --decode)
    URL=$(kubectl get secret nl-wallet-dependency-track-secret -o jsonpath='{.data.url}' | base64 --decode)
    # Read and encode the BOM file
    BOM_CONTENTS=$(cat "$BOM_FILENAME" | base64 -w 0)
    # Remove UTF-8 BOM if present
    case $BOM_CONTENTS in
      77u/*) BOM_CONTENTS=${BOM_CONTENTS:4};;
    esac
    # Create JSON payload
    BOM_PAYLOAD="{\"project\": \"$PROJECT_ID\", \"bom\": \"$BOM_CONTENTS\"}"
    echo "$BOM_PAYLOAD" > /tmp/bomPayload.json
    # Send to Dependency-Track
    curl -f -X PUT "$URL" \
      -H "X-API-Key: $API_KEY" \
      -H "Content-Type: application/json" \
      --data-binary @/tmp/bomPayload.json
  allow_failure: true
