build-mock-trigger:
  rules:
    - !reference [.default-or-release, rules]
  needs:
    - job: test-flutter
      artifacts: false
    - job: test-flutter-ui
      artifacts: false
    - job: test-codegen
      artifacts: false
    - job: test-rust
      artifacts: false
    - job: test-rust-doctest
      artifacts: false
    - job: test-rust-compilation-android
      artifacts: false
    - job: test-ios
      artifacts: false
    - job: test-rust-compilation-ios
      artifacts: false
  trigger:
    include:
      - local: .gitlab-ci.yml
  variables:
    BUILD: 'mock'
  when: manual
  allow_failure: true

build-demo-trigger:
  rules:
    - !reference [.default-or-release, rules]
  needs:
    - job: test-flutter
      artifacts: false
    - job: test-flutter-ui
      artifacts: false
    - job: test-codegen
      artifacts: false
    - job: test-rust
      artifacts: false
    - job: test-rust-doctest
      artifacts: false
    - job: test-rust-compilation-android
      artifacts: false
    - job: test-ios
      artifacts: false
    - job: test-rust-compilation-ios
      artifacts: false
  trigger:
    include:
      - local: .gitlab-ci.yml
  variables:
    BUILD: 'demo'

trigger-scheduled-automation-tests:
  rules:
    - !reference [.default-or-release, rules]
  needs:
    - job: deploy-mock-relying-party-ont
      artifacts: false
      optional: true
    - job: deploy-wallet-provider-ont
      artifacts: false
      optional: true
    - job: deploy-pid-issuer-ont
      artifacts: false
      optional: true
    - job: deploy-update-policy-server-ont
      artifacts: false
      optional: true
    - job: deploy-gba-hc-converter-ont
      artifacts: false
      optional: true
    - job: deploy-gba-fetch-frontend-ont
      artifacts: false
      optional: true
  trigger:
    include:
      - local: .gitlab-ci.yml
  variables:
    SCHEDULED: true
  when: manual
  allow_failure: true
