FROM ${HARBOR_REGISTRY}/gcr-io-proxy/distroless/cc-debian12:debug-nonroot

COPY --chown=nonroot ./target/x86_64-unknown-linux-gnu/debug/gba_fetch .
COPY --chown=nonroot ./target/x86_64-unknown-linux-musl/debug/gba_fetch ./gba_fetch_musl

ENTRYPOINT ["sh"]
