{{- if .Values.ingress.enabled }}
{{ $name := include "common.names.fullname" . }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nl-{{ $name }}-internal
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingressVpn.hostname | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "common.names.fullname" . }}
                port:
                  name: http-internal
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.ingressVpn.hostname | quote }}
      secretName: wildcard-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nl-{{ $name }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    odcn.rijksapps.nl/inet-loadbalancer-hostnames: {{ .Values.verificationServer.hostname | quote }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains"
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Content-Security-Policy: default-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'";
      more_set_headers "X-Permitted-Cross-Domain-Policies: none";
      more_set_headers "Cross-Origin-Resource-Policy: same-origin";
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.verificationServer.hostname | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "common.names.fullname" . }}
                port:
                  name: http
            path: /{{ .Values.verificationServer.contextPath }}/(.*)
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ .Values.verificationServer.hostname }}
      secretName: {{ .Values.ingress.tlsSecretName | quote }}
{{ end }}
