{{ $chart := . -}}
{{ $hostSuffix := ternary "-pooler-rw" "-rw" .Values.pooling.enabled }}
{{- range .Values.databases }}
{{ $fullName := print $chart.Release.Name "-" . | replace "_" "-" }}
{{ $host := print $chart.Release.Name $hostSuffix }}
{{ $port := "5432" }}
{{ $password := include "common.secrets.getSecretByName" (dict "release" $chart.Release "name" $fullName) | trim }}
{{ $url := print "postgres://" . ":" $password "@" $host ":" $port "/" . }}
---
apiVersion: v1
data:
  host: {{ $host | b64enc | quote }}
  port: {{ $port | b64enc | quote }}
  username: {{ . | b64enc | quote }}
  password: {{ $password | b64enc | quote }}
  database: {{ . | b64enc | quote }}
  url: {{ $url | b64enc | quote }}
kind: Secret
metadata:
  name: {{ $fullName }}
type: kubernetes.io/basic-auth
{{- end }}
