// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionOptions = { usecase: string }

export type SessionResponse = { status_url: URL; session_token: string }
