apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
  ports:
    - name: update-policy-server-http
      port: 3002
      targetPort: ups-port
      protocol: TCP
