[package]
name = "pid_issuer_migrations"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "pid_issuer_migrations"
doctest = false

[dependencies]
sea-orm-migration = { workspace = true, features = ["cli", "runtime-tokio-rustls", "sqlx-postgres"] }
tokio = { workspace = true, features = ["rt-multi-thread", "parking_lot", "macros"] }

server_utils_migrations.path = "../../server_utils/migrations"
