apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    {{- include "common.labels.selectorLabels" . | nindent 4 }}
  ports:
    - name: demo-issuer-web-http
      port: 3005
      targetPort: demo-iw-port
      protocol: TCP
    - name: demo-issuer-issuance-http
      port: 3006
      targetPort: demo-ii-port
      protocol: TCP
