---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "${INTERNAL_ISSUANCE_SERVER_URL}"
    includePaths:
    - "${INTERNAL_ISSUANCE_SERVER_URL}.*"
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
    technology:
      exclude: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    type: "url"
    fileName: "INTERNAL_ISSUANCE_SERVER_urls.txt"
  name: "import"
  type: "import"
- parameters:
    context: "Default Context"
    user: ""
    policy: ""
    maxRuleDurationInMins: 0
    maxScanDurationInMins: 0
    addQueryParam: true
    delayInMs: 0
    handleAntiCSRFTokens: true
    injectPluginIdInHeader: true
    scanHeadersAllRequests: true
    threadPerHost: 24
    maxAlertsPerRule: 0
  policyDefinition:
    defaultStrength: "medium"
    defaultThreshold: "medium"
    rules: []
  name: "activeScan"
  type: "activeScan"
- parameters:
    template: "modern"
    theme: "console"
    reportDir: "${CI_PROJECT_DIR}/zapreports"
    reportFile: ""
    reportTitle: "INTERNAL_ISSUANCE_SERVER ZAP Scanning Report"
    reportDescription: ""
    displayReport: false
  risks:
  - "low"
  - "medium"
  - "high"
  confidences:
  - "low"
  - "medium"
  - "high"
  - "confirmed"
  sections:
  - "passingrules"
  - "instancecount"
  - "alertdetails"
  - "alertcount"
  - "params"
  - "chart"
  - "statistics"
  sites: []
  name: "report"
  type: "report"
- parameters:
    template: "traditional-xml"
    reportDir: "${CI_PROJECT_DIR}/zapreports"
    reportFile: "INTERNAL_ISSUANCE_SERVER-zap.xml"
    reportTitle: "INTERNAL_ISSUANCE_SERVER ZAP Scanning Report"
    reportDescription: ""
    displayReport: false
  risks:
  - "info"
  - "low"
  - "medium"
  - "high"
  confidences:
  - "falsepositive"
  - "low"
  - "medium"
  - "high"
  - "confirmed"
  sites: []
  name: "report"
  type: "report"
- parameters:
    template: "traditional-json"
    reportDir: "${CI_PROJECT_DIR}/zapreports"
    reportFile: "INTERNAL_ISSUANCE_SERVER-zap.json"
    reportTitle: "INTERNAL_ISSUANCE_SERVER ZAP Scanning Report"
    reportDescription: ""
    displayReport: false
  risks:
    - "info"
    - "low"
    - "medium"
    - "high"
  confidences:
    - "falsepositive"
    - "low"
    - "medium"
    - "high"
    - "confirmed"
  sites: []
  name: "report"
  type: "report"
