---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "${PID_ISSUER_BASE_URL}"
    includePaths:
    - "${PID_ISSUER_BASE_URL}/.*"
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
    technology:
      exclude: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- alertFilters:
# False positive analysis in pwv-3375 showed that this is not a vulnerability
    - ruleId: "40025"
      ruleName: "Proxy Disclosure (40025)"
      context: ""
      newRisk: "False Positive"
      parameter: ""
      parameterRegex: false
      url: ""
      urlRegex: false
      attack: ""
      attackRegex: false
      evidence: ""
      evidenceRegex: false
      methods: [ ]
  parameters:
    deleteGlobalAlerts: false
  name: "alertFilter"
  type: "alertFilter"
- parameters:
    type: "url"
    fileName: "PID_ISSUER_urls.txt"
  name: "import"
  type: "import"
- parameters:
    context: "Default Context"
    user: ""
    policy: ""
    maxRuleDurationInMins: 0
    maxScanDurationInMins: 0
    addQueryParam: true
    delayInMs: 0
    handleAntiCSRFTokens: true
    injectPluginIdInHeader: true
    scanHeadersAllRequests: true
    threadPerHost: 24
    maxAlertsPerRule: 0
  policyDefinition:
    defaultStrength: "medium"
    defaultThreshold: "medium"
    rules: []
  name: "activeScan"
  type: "activeScan"
- parameters:
    template: "modern"
    theme: "console"
    reportDir: "${CI_PROJECT_DIR}/zapreports"
    reportFile: ""
    reportTitle: "PID_ISSUER ZAP Scanning Report"
    reportDescription: ""
    displayReport: false
  risks:
  - "low"
  - "medium"
  - "high"
  confidences:
  - "low"
  - "medium"
  - "high"
  - "confirmed"
  sections:
  - "passingrules"
  - "instancecount"
  - "alertdetails"
  - "alertcount"
  - "params"
  - "chart"
  - "statistics"
  sites: []
  name: "report"
  type: "report"
- parameters:
    template: "traditional-xml"
    reportDir: "${CI_PROJECT_DIR}/zapreports"
    reportFile: "PID_ISSUER-zap.xml"
    reportTitle: "PID_ISSUER ZAP Scanning Report"
    reportDescription: ""
    displayReport: false
  risks:
  - "info"
  - "low"
  - "medium"
  - "high"
  confidences:
  - "falsepositive"
  - "low"
  - "medium"
  - "high"
  - "confirmed"
  sites: []
  name: "report"
  type: "report"
- parameters:
    template: "traditional-json"
    reportDir: "${CI_PROJECT_DIR}/zapreports"
    reportFile: "PID_ISSUER-zap.json"
    reportTitle: "PID_ISSUER ZAP Scanning Report"
    reportDescription: ""
    displayReport: false
  risks:
    - "info"
    - "low"
    - "medium"
    - "high"
  confidences:
    - "falsepositive"
    - "low"
    - "medium"
    - "high"
    - "confirmed"
  sites: []
  name: "report"
  type: "report"
