// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'attestation.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FlutterConfiguration {
  final int inactiveWarningTimeout;
  final int inactiveLockTimeout;
  final int backgroundLockTimeout;
  final List<PidAttestation> pidAttestations;
  final String staticAssetsBaseUrl;
  final (String, String)? maintenanceWindow;
  final String version;
  final String environment;

  const FlutterConfiguration({
    required this.inactiveWarningTimeout,
    required this.inactiveLockTimeout,
    required this.backgroundLockTimeout,
    required this.pidAttestations,
    required this.staticAssetsBaseUrl,
    this.maintenanceWindow,
    required this.version,
    required this.environment,
  });

  @override
  int get hashCode =>
      inactiveWarningTimeout.hashCode ^
      inactiveLockTimeout.hashCode ^
      backgroundLockTimeout.hashCode ^
      pidAttestations.hashCode ^
      staticAssetsBaseUrl.hashCode ^
      maintenanceWindow.hashCode ^
      version.hashCode ^
      environment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterConfiguration &&
          runtimeType == other.runtimeType &&
          inactiveWarningTimeout == other.inactiveWarningTimeout &&
          inactiveLockTimeout == other.inactiveLockTimeout &&
          backgroundLockTimeout == other.backgroundLockTimeout &&
          pidAttestations == other.pidAttestations &&
          staticAssetsBaseUrl == other.staticAssetsBaseUrl &&
          maintenanceWindow == other.maintenanceWindow &&
          version == other.version &&
          environment == other.environment;
}

class PidAttestation {
  final Format format;
  final String attestationType;

  const PidAttestation({
    required this.format,
    required this.attestationType,
  });

  @override
  int get hashCode => format.hashCode ^ attestationType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PidAttestation &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          attestationType == other.attestationType;
}
