// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'attestation.dart';
import 'image.dart';
import 'instruction.dart';
import 'localize.dart';
import 'organization.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'revocation.dart';
part 'disclosure.freezed.dart';

@freezed
sealed class AcceptDisclosureResult with _$AcceptDisclosureResult {
  const AcceptDisclosureResult._();

  const factory AcceptDisclosureResult.ok({
    String? returnUrl,
  }) = AcceptDisclosureResult_Ok;
  const factory AcceptDisclosureResult.instructionError({
    required WalletInstructionError error,
  }) = AcceptDisclosureResult_InstructionError;
}

@freezed
sealed class CloseProximityDisclosureFlutterUpdate with _$CloseProximityDisclosureFlutterUpdate {
  const CloseProximityDisclosureFlutterUpdate._();

  const factory CloseProximityDisclosureFlutterUpdate.connected() = CloseProximityDisclosureFlutterUpdate_Connected;
  const factory CloseProximityDisclosureFlutterUpdate.deviceRequestReceived() =
      CloseProximityDisclosureFlutterUpdate_DeviceRequestReceived;
  const factory CloseProximityDisclosureFlutterUpdate.disconnected() =
      CloseProximityDisclosureFlutterUpdate_Disconnected;
  const factory CloseProximityDisclosureFlutterUpdate.errored({
    required String error,
  }) = CloseProximityDisclosureFlutterUpdate_Errored;
}

class DisclosureOptions {
  final List<AttestationPresentation> field0;

  const DisclosureOptions({
    required this.field0,
  });

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DisclosureOptions && runtimeType == other.runtimeType && field0 == other.field0;
}

enum DisclosureSessionType {
  SameDevice,
  CrossDevice,
  CloseProximity,
}

enum DisclosureType {
  Login,
  Regular,
}

class MissingAttribute {
  final List<LocalizedString> labels;

  const MissingAttribute({
    required this.labels,
  });

  @override
  int get hashCode => labels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is MissingAttribute && runtimeType == other.runtimeType && labels == other.labels;
}

class RequestPolicy {
  final BigInt? dataStorageDurationInMinutes;
  final bool dataSharedWithThirdParties;
  final bool dataDeletionPossible;
  final String policyUrl;

  const RequestPolicy({
    this.dataStorageDurationInMinutes,
    required this.dataSharedWithThirdParties,
    required this.dataDeletionPossible,
    required this.policyUrl,
  });

  @override
  int get hashCode =>
      dataStorageDurationInMinutes.hashCode ^
      dataSharedWithThirdParties.hashCode ^
      dataDeletionPossible.hashCode ^
      policyUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequestPolicy &&
          runtimeType == other.runtimeType &&
          dataStorageDurationInMinutes == other.dataStorageDurationInMinutes &&
          dataSharedWithThirdParties == other.dataSharedWithThirdParties &&
          dataDeletionPossible == other.dataDeletionPossible &&
          policyUrl == other.policyUrl;
}

@freezed
sealed class StartDisclosureResult with _$StartDisclosureResult {
  const StartDisclosureResult._();

  const factory StartDisclosureResult.request({
    required Organization relyingParty,
    required RequestPolicy policy,
    required List<DisclosureOptions> disclosureOptions,
    required bool sharedDataWithRelyingPartyBefore,
    required DisclosureSessionType sessionType,
    required List<LocalizedString> requestPurpose,
    required String requestOriginBaseUrl,
    required DisclosureType requestType,
  }) = StartDisclosureResult_Request;
  const factory StartDisclosureResult.requestAttributesMissing({
    required Organization relyingParty,
    required List<MissingAttribute> missingAttributes,
    required bool sharedDataWithRelyingPartyBefore,
    required DisclosureSessionType sessionType,
    required List<LocalizedString> requestPurpose,
    required String requestOriginBaseUrl,
  }) = StartDisclosureResult_RequestAttributesMissing;
}
