// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'image.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `try_from`

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SanitizedSvg>>
abstract class SanitizedSvg implements RustOpaqueInterface {
  String xml();
}

@freezed
sealed class Image with _$Image {
  const Image._();

  const factory Image.jpeg({
    required Uint8List data,
  }) = Image_Jpeg;
  const factory Image.png({
    required Uint8List data,
  }) = Image_Png;
  const factory Image.svg({
    required SanitizedSvg svg,
  }) = Image_Svg;
  const factory Image.asset({
    required String path,
  }) = Image_Asset;
}

class ImageWithMetadata {
  final Image image;
  final String altText;

  const ImageWithMetadata({
    required this.image,
    required this.altText,
  });

  @override
  int get hashCode => image.hashCode ^ altText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageWithMetadata &&
          runtimeType == other.runtimeType &&
          image == other.image &&
          altText == other.altText;
}
