// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'image.freezed.dart';

@freezed
sealed class Image with _$Image {
  const Image._();

  const factory Image.svg({
    required SanitizedSvg xml,
  }) = Image_Svg;
  const factory Image.png({
    required Uint8List data,
  }) = Image_Png;
  const factory Image.jpeg({
    required Uint8List data,
  }) = Image_Jpeg;
  const factory Image.asset({
    required String path,
  }) = Image_Asset;
}

class ImageWithMetadata {
  final Image image;
  final String altText;

  const ImageWithMetadata({
    required this.image,
    required this.altText,
  });

  @override
  int get hashCode => image.hashCode ^ altText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageWithMetadata &&
          runtimeType == other.runtimeType &&
          image == other.image &&
          altText == other.altText;
}

class SanitizedSvg {
  final String field0;

  const SanitizedSvg({
    required this.field0,
  });

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is SanitizedSvg && runtimeType == other.runtimeType && field0 == other.field0;
}
