// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'image.dart';
import 'localize.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Organization {
  final String legalName;
  final String displayName;
  final List<LocalizedString> description;
  final Image? image;
  final String? webUrl;
  final String? privacyPolicyUrl;
  final String? identifier;
  final List<LocalizedString>? city;
  final List<LocalizedString> category;
  final List<LocalizedString>? department;
  final String countryCode;

  const Organization({
    required this.legalName,
    required this.displayName,
    required this.description,
    this.image,
    this.webUrl,
    this.privacyPolicyUrl,
    this.identifier,
    this.city,
    required this.category,
    this.department,
    required this.countryCode,
  });

  @override
  int get hashCode =>
      legalName.hashCode ^
      displayName.hashCode ^
      description.hashCode ^
      image.hashCode ^
      webUrl.hashCode ^
      privacyPolicyUrl.hashCode ^
      identifier.hashCode ^
      city.hashCode ^
      category.hashCode ^
      department.hashCode ^
      countryCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Organization &&
          runtimeType == other.runtimeType &&
          legalName == other.legalName &&
          displayName == other.displayName &&
          description == other.description &&
          image == other.image &&
          webUrl == other.webUrl &&
          privacyPolicyUrl == other.privacyPolicyUrl &&
          identifier == other.identifier &&
          city == other.city &&
          category == other.category &&
          department == other.department &&
          countryCode == other.countryCode;
}
