// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ValidityWindow {
  final String? validFrom;
  final String? validUntil;

  const ValidityWindow({
    this.validFrom,
    this.validUntil,
  });

  @override
  int get hashCode => validFrom.hashCode ^ validUntil.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValidityWindow &&
          runtimeType == other.runtimeType &&
          validFrom == other.validFrom &&
          validUntil == other.validUntil;
}
