// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'wallet_state.freezed.dart';

@freezed
sealed class WalletState with _$WalletState {
  const WalletState._();

  const factory WalletState.ready() = WalletState_Ready;
  const factory WalletState.transferring({
    required WalletTransferRole role,
  }) = WalletState_Transferring;
}

enum WalletTransferRole {
  Source,
  Destination,
}
